### ISSUE TITLE
[Bug]: attempt to index field 'choices' (a nil value)

### ISSUE THREAD

**Issue by olimorris** [jackMort/ChatGPT.nvim#10]
If I open `chatgpt` and type anything, I get the following error:

```text
Error executing vim.schedule lua callback: .../site/pack/packer/start/chatgpt.nvim/lua/chatgpt/api.lua:42: attempt to index field 'choices' (a nil value)
stack traceback:
        .../site/pack/packer/start/chatgpt.nvim/lua/chatgpt/api.lua:42: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

My config is:

```lua
  chatgpt.setup({
    welcome_message = "",
    chat_input = {
    prompt = "   ",
    }
  })
```

**Comment by olimorris** [comment]
Bizarrely, I just refreshed my API key and it seems to be working now. Not sure if anyone came across this error?

**Comment by jackMort** [comment]
In most cases, the problem is the wrong or expired API key.

**Comment by olimorris** [comment]
Was likely an expired one in my case 👍🏼

**Comment by gipo355** [comment]
can confirm, this bug is happening to me too.
Verified multiple times the correct key was inserted and loaded in the shell, generated new one too.

**Comment by jtws** [comment]
I get the same error with a brand new API key mid-conversation. I asked 20-30 questions and after the last question I got this error and ChatGPT was stuck showing the `loading` animation and had to be closed. Starting it again it works fine for a while until I hit this error again. Is there some kind of rate limiting on the API or limit on discussion length? In any case this error should be handled and not leave the plugin in a stuck state requiring termination. 

There probably should be a retry functionality with exponential back-off and fallback to starting a new conversation with the initial prompt.
