### ISSUE TITLE
Anyone tried that this plugin works 3.5 turbo?

### ISSUE THREAD

**Issue by PorcoRosso85** [jackMort/ChatGPT.nvim#104]
https://platform.openai.com/docs/guides/chat
Anyone tried that this plugin works chatgpt api 3.5 turbo?

OR
https://platform.openai.com/docs/guides/code/introduction
Codex?

**Comment by Zinnusl** [comment]
It is set to 3.5 turbo by default and it works. I also changed it to gpt-4 and it works fine.

**Comment by PorcoRosso85** [comment]
Excellent.
Thanks.

**Comment by dragonofdeath** [comment]
@Zinnusl can I ask how you configured it to work with gpt-4? I have access to gpt-4 in web interface, but cant get working it with this plugin

**Comment by Zinnusl** [comment]
> @Zinnusl can I ask how you configured it to work with gpt-4? I have access to gpt-4 in web interface, but cant get working it with this plugin

If, with web interface you mean ChatGPT Plus, that will not work with this.
For this plugin you will need access to the API here: https://platform.openai.com/account/api-keys
If I misunderstand and you do have that set up, you also need to sign up for the wait list here: https://openai.com/waitlist/gpt-4-api
Once you do have access you can change the model by pressing <ctrl-o> with the :ChatGPT modal open. (Or set it as the default in the plugin internals)

**Comment by dragonofdeath** [comment]
oh, yes,  I thought ChatGPT Plus gives that access. Thank you @Zinnusl, I will join the waiting list.

**Comment by lpanebr** [comment]
Thanks was wanting this also!

**Comment by Zinnusl** [comment]
@lpanebr You can press ctrl-o when in insert mode in the prompt line to open up the settings, too. Then navigate the windows with Tab and up and down arrow.

**Comment by lpanebr** [comment]
Ow, now I see. I need to leave the config as is and change on the prompt window by Tab then Enter to edit the value!
![image](https://user-images.githubusercontent.com/129185/230474431-fc9310de-a428-4d02-8403-f8dcaa043205.png)

It works! 
THANKS!

**Comment by sudoFerraz** [comment]
Hi, when switching to gpt-4 I get a prompt with:
`// API ERROR: The model: `gpt-4` does not exist`
