### ISSUE TITLE
API Error - Invalid JSON due to 'utf-8' codec decoding issue

### ISSUE THREAD

**Issue by Zinnusl** [jackMort/ChatGPT.nvim#106]
When using the ChatGPT plugin for Neovim, an API error occurs stating that the request contains invalid JSON.
The error message is as follows: `'utf-8' codec can't decode byte 0xfc in position 62: invalid start byte`. 

Steps to reproduce:
1. :ChatGPT
2. Enter "über­ge­ben" into the prompt field ("|" also seems to cause this error)
3. Press Enter
4. API Error

Env.
Windows
Neovim 0.8.0
Newest Plugin Version (as of posting this issue)
Changed model to gpt-4 instead of gpt-3.5-turbo

**Comment by lucasquin** [comment]
A solução do [Zinnusl](https://github.com/Zinnusl) funcionou para mim. Pessoas como você são maravilhosas ;)
