### ISSUE TITLE
not working in neovim HEAD

### ISSUE THREAD

**Issue by nfwyst** [jackMort/ChatGPT.nvim#112]
input something and press enter key, has no effect except that the prompt window becomes taller
<img width="1567" alt="截屏2023-03-20 11 09 52" src="https://user-images.githubusercontent.com/35720450/226237731-6008719c-2ca9-4266-b22b-ca8129528c75.png">
and finally the following error will appear
Error executing vim.schedule lua callback: ...site/pack/packer/start/nui.nvim/lua/nui/popup/border.lua:541: 'height' key must be a positive Integer
stack traceback:
        [C]: in function 'nvim_win_set_config'
        ...site/pack/packer/start/nui.nvim/lua/nui/popup/border.lua:541: in function '_relayout'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:359: in function 'set_layout'
        ...site/pack/packer/start/nui.nvim/lua/nui/layout/float.lua:89: in function 'process'
        ...site/pack/packer/start/nui.nvim/lua/nui/layout/float.lua:123: in function 'process'
        .../site/pack/packer/start/nui.nvim/lua/nui/layout/init.lua:198: in function '_process_layout'
        .../site/pack/packer/start/nui.nvim/lua/nui/layout/init.lua:395: in function 'update'
        ...site/pack/packer/opt/ChatGPT.nvim/lua/chatgpt/module.lua:80: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

**Comment by jackMort** [comment]
Ctrl+enter to submit, it remap submit keymap, see readme for more
