### ISSUE TITLE
Lazy plugin manager configuration, disable lazy loading

### ISSUE THREAD

**Issue by doctorfree** [jackMort/ChatGPT.nvim#115]
I was unable to get lazy loading of ChatGPT plugin using the Lazy plugin manager. If I disable lazy loading then ChatGPT loads and works properly. With lazy loading enabled the response window spun at "loading".

Perhaps it is possible to configure Lazy loading with some event. I am still experimenting.

Here is a ChatGPT plugin configuration for use with the Lazy plugin manager that works for me. I simply disable lazy loading:

```lua
    {
      "jackMort/ChatGPT.nvim",
      lazy = false,
      dependencies = {
        "MunifTanjim/nui.nvim",
        "nvim-lua/plenary.nvim",
        "nvim-telescope/telescope.nvim",
      },
      config = function()
        require("chatgpt").setup({
          -- config here
        })
      end,
    }
```

**Comment by onlytracks** [comment]
I just set this up myself and admittedly am still learning Lazy, but I was able to get it to lazy load with the `cmd` option:
```lua
  {
    "jackMort/ChatGPT.nvim",
    cmd = "ChatGPT",
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
    },
    config = function()
      require("chatgpt").setup()
    end,
  },
}
```
It stays unloaded until I use the `:ChatGPT` command to load it and open the plugin.
