### ISSUE TITLE
Edit with instructions lua callback error

### ISSUE THREAD

**Issue by linulas** [jackMort/ChatGPT.nvim#120]
Getting this error when submitting prompts for "Edit with instructions":

```
Error executing vim.schedule lua callback: .../pack/packer/opt/ChatGPT.nvim/lua/chatgpt/code_edits.lua:99: attempt to index local 'usage' (a nil value)
stack traceback:
        .../pack/packer/opt/ChatGPT.nvim/lua/chatgpt/code_edits.lua:99: in function 'cb'
        ...im/site/pack/packer/opt/ChatGPT.nvim/lua/chatgpt/api.lua:63: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Any ideas?

**Comment by Bryley** [comment]
I'm getting the same error. It looks like the issue is to do with the `code-davinci-edit-001` and `text-davinci-edit-001` models no longer existing for some reason. OpenAI might have deprecated it in replace for something else.

[See this post on OpenAI Forums](https://community.openai.com/t/the-model-text-davinci-edit-001-does-not-exist/116144)

You can also see that the [OpenAI Playground](https://platform.openai.com/playground?mode=edit&model=code-davinci-edit-001) that uses this model doesn't work either which proves this is an issue with OpenAI and not the plugin.

**Comment by linulas** [comment]
> I'm getting the same error. It looks like the issue is to do with the `code-davinci-edit-001` and `text-davinci-edit-001` models no longer existing for some reason. OpenAI might have deprecated it in replace for something else.
> 

Ah yes, it looks like you're right, OpenAI have discontinued the code-davinci:001 model as of yesterday in favor of the more performant models in the GPT-3.5 family: 

_On March 23rd, we will discontinue support for the Codex API. All customers will have to transition to a different model. Codex was initially introduced as a free limited beta in 2021, and has maintained that status to date. Given the advancements of our newest GPT-3.5 models for coding tasks, we will no longer be supporting Codex and encourage all customers to transition to GPT-3.5-Turbo. About GPT-3.5-Turbo GPT-3.5-Turbo is the most cost effective and performant model in the GPT-3.5 family. It can both do coding tasks while also being complemented with flexible natural language capabilities._

_You can learn more through: GPT-3.5 model overview Chat completions guide_

_Models affected The following models will be discontinued: code-cushman:001 code-cushman:002 **code-davinci:001** code-davinci:002_

_We understand this transition may be temporarily inconvenient, but we are confident it will allow us to increase our investment in our latest and most capable models._

_—The OpenAI team_

[https://news.ycombinator.com/item?id=35242069](https://news.ycombinator.com/item?id=35242069)

**Comment by cmpadden** [comment]
@linulas the `code-davinci-edit-001` is once again available.

```bash
$ models=$(curl -s https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY")
$ jq -r .data[].id  <(echo "$models") | sort | grep code-
ada-code-search-code
ada-code-search-text
babbage-code-search-code
babbage-code-search-text
code-davinci-edit-001
code-search-ada-code-001
code-search-ada-text-001
code-search-babbage-code-001
code-search-babbage-text-001
```

I've confirmed that the `:ChatGPTEditWithInstructions` command is working as expected with the default configuration.

This issue could likely be closed for now -- hope this helps!
