### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rob-3** [jackMort/ChatGPT.nvim#123]
Any plans to put this repo under an open-source license? I try to keep my setup fully open-source when possible.

**Comment by jackMort** [comment]
sure, what license are you suggesting?

**Comment by rob-3** [comment]
https://choosealicense.com/licenses/ is a good resource for some common ones. Most plugins I see are something permissive like MIT/Apache 2.0/BSD, which mostly allow others to do whatever they want with your code, usually with attribution to you. There are also stricter options like GPL/AGPL if you want to require that changes to the project are made available to you.

Neovim itself uses Apache 2.0 except for any original vim code, which is under a custom vim license. https://github.com/neovim/neovim/blob/master/LICENSE.txt

**Comment by jackMort** [comment]
done, thanks @rob-3 !
