### ISSUE TITLE
Error when trying to scroll up/down in a chat session.

### ISSUE THREAD

**Issue by id-b3** [jackMort/ChatGPT.nvim#126]
> E5108: Error executing lua: ....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/module.lua:57: Error executing lua: ....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/modu
> le.lua:58: Vim(normal):E21: Cannot make changes, 'modifiable' is off
> stack traceback:
>         [C]: in function 'cmd'
>         ....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/module.lua:58: in function <....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/module.lua:57>
>         [C]: in function 'nvim_win_call'
>         ....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/module.lua:57: in function 'scroll_chat'
>         ....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/module.lua:161: in function <....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/module.lua:160>
> stack traceback:
>         [C]: in function 'nvim_win_call'
>         ....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/module.lua:57: in function 'scroll_chat'
>         ....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/module.lua:161: in function <....config/nvim/plugged/ChatGPT.nvim/lua/chatgpt/module.lua:160>
> 

I get the above error every time I press C-u/C-d in the chat session. Also, I C-u/C-d does nothing if the prompt entry box is in normal mode, it only 'works' when in insert mode. Can someone help with this?

**Comment by cmpadden** [comment]
I also get this error.

Scrolling happens using `<C-e>` and `<C-y>` as seen here:

https://github.com/jackMort/ChatGPT.nvim/blob/main/lua/chatgpt/module.lua#L56

This error is being thrown because some modifications are happening to the chat window, but it has `set nomodifiable`.

What's strange is `<C-e>` and `<C-y>` typically work fine when a buffer cannot be modified. So something else must be happening, I will look into it further, but if anyone has any pointers let me know!

**Comment by cmpadden** [comment]
Another observation, when using `<C-u>` and `<C-d>` with the buffer modifiable, it is entering a string of 5s.
![image](https://user-images.githubusercontent.com/5807118/229181045-12151a65-9f33-4ab6-af33-b84587d5541f.png)

**Comment by cmpadden** [comment]
Digging into it, and it's because the command being generated is `normal! 24.5^E`. `math.abs` should instead be `math.floor`.

You can find the fix in this PR https://github.com/jackMort/ChatGPT.nvim/pull/130

Cheers!
