### ISSUE TITLE
Entering prompt causes new line.

### ISSUE THREAD

**Issue by Montana** [jackMort/ChatGPT.nvim#135]
Hi everyone, 

First off, I want to thank @jackMort. This is a great plugin, and I want to thank you for your work on this and helping me get the install going. 

The issue I'm having is when entering a new prompt, it starts a new line, this can be fixed by closing the session out and restarting it via running `nvim` again and reopening it. I've attached a screenshot. 

Is this caused by ratelimiting?  

I've tried: 

```lua
use({
    "jackMort/ChatGPT.nvim",
    config = function()
      require("chatgpt").setup({
        keymaps = {
          submit = "<C-s>"
        }
      })
    end,
    requires = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    }
  })
```
Still to no avail. Any help would be greatly appreciated.

<img width="1121" alt="Screenshot 2023-04-04 at 9 08 40 AM" src="https://user-images.githubusercontent.com/20936398/229852305-47a06848-498e-407d-b4a6-52862d0c3f7a.png">

Cheers,
Montana Mendy

**Comment by jackMort** [comment]
try remap to something else, it may be not supported by your terminal, here are some solutions: https://github.com/jackMort/ChatGPT.nvim/issues/105

**Comment by Montana** [comment]
Thank you @jackMort!
