### ISSUE TITLE
Can't submit query due to json_encode error

### ISSUE THREAD

**Issue by mmngreco** [jackMort/ChatGPT.nvim#136]
Thank you for provide this awesome plugin. I was able to use before but now I've get this error when I submit my request

![image](https://user-images.githubusercontent.com/6231413/230118045-a49d088a-be1a-4d07-b750-4a6924fddd67.png)

I'm using xterm but the happens in others (alacritty, kitty, wezterm)

**Comment by comiluv** [comment]
Does this error occur on a new conversation too (after pressing <C-n>) or only happens when loading an existing conversation?
