### ISSUE TITLE
format code wrapped in ``` 

### ISSUE THREAD

**Issue by jackMort** [jackMort/ChatGPT.nvim#138]
Find way to add syntax highlighting for code

**Comment by cmpadden** [comment]
When code blocks have the language specified, I am able to get tree-sitter syntax highlighting. Would this help in this scenario?

![image](https://user-images.githubusercontent.com/5807118/230453713-4d6a1677-29c2-4b72-86bf-69e5bc369803.png)

**Comment by 00sapo** [comment]
Is this issue related to the chat or to other parts?

**Comment by jackMort** [comment]
@cmpadden could you share some code snippet/example how did you achieve that, I'm not familiar with tree-sitter yet

**Comment by jackMort** [comment]
yes @00sapo it would be great to add syntax highlighting for code blocks in chat

**Comment by akinsho** [comment]
You can do this by either setting the filetype to markdown like the above or in `nvim-0.9` you can tell the `chatgpt` filetype to use the `markdown` parser.

```lua
vim.treesitter.language.register('markdown', 'chatgpt'),
```
You can do the above in the context of the output window or if user is the one doing it you can use a filetype autocommand
