### ISSUE TITLE
ChatGPTRun Command throws error

### ISSUE THREAD

**Issue by Gerzulet** [jackMort/ChatGPT.nvim#142]
Hi! 
I am using Garuda Linux
I am getting this error whenever i try to use the ChatGPTRun command: 

`Error executing vim.schedule lua callback: ...er/start/ChatGPT.nvim/lua/chatgpt/flows/actions/base.lua:44: att
empt to index a nil value
stack traceback:
...er/start/ChatGPT.nvim/lua/chatgpt/flows/actions/base.lua:44: in function 'get_visual_selection'
...er/start/ChatGPT.nvim/lua/chatgpt/flows/actions/base.lua:66: in function 'mark_selection_with_signs
'
...er/start/ChatGPT.nvim/lua/chatgpt/flows/actions/base.lua:101: in function 'set_loading'
...art/ChatGPT.nvim/lua/chatgpt/flows/actions/chat/init.lua:70: in function <...art/ChatGPT.nvim/lua/c
hatgpt/flows/actions/chat/init.lua:69>`

Its the same for every action i put .

**Comment by 00sapo** [comment]
Hi, can you write the command you use?

CatGPTRun expects at least one argument. See the readme for more details

**Comment by Gerzulet** [comment]
The command was :ChatGPTRun explain_code. 
After reading your comment i made it to work, i was using the command with no block of code selected.
I selected the block of code i wanted to explain and it worked. 
The only thing, and i dont know if this is normal, is that, in this case, the explanation of code is directly pasted in my file, forcing me to undo the changes to return to the code it had. 

Thanks for your help.

**Comment by 00sapo** [comment]
> The only thing, and i dont know if this is normal, is that, in this case, the explanation of code is directly pasted in my file, forcing me to undo the changes to return to the code it had.

You are right, the error is that explain_code action has two strategies set up:

https://github.com/jackMort/ChatGPT.nvim/blob/3ea19ba666e226ac33c8e00c7bf99e81931d7c86/lua/chatgpt/flows/actions/actions.json#L122
