### ISSUE TITLE
Index global wk

### ISSUE THREAD

**Issue by kamalkech** [jackMort/ChatGPT.nvim#144]
I get this error:

```
Error detected while processing /home/kamal/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/.config/nvim/lua/user/chatgpt.lua:2: attempt to index global 'wk' (a nil value)
stack traceback:
        /home/.config/nvim/lua/user/chatgpt.lua:2: in main chunk
        [C]: in function 'require'
        /home/.config/nvim/init.lua:23: in main chunk
```

**Comment by 00sapo** [comment]
Can you explain how you get this error? Why do you have chatgpt.lua inside your config folder?

**Comment by kamalkech** [comment]
- Can you explain how you get this error: i follow just the readme
- Why do you have chatgpt.lua inside your config folder :
![image](https://user-images.githubusercontent.com/1313428/230787048-38f83faf-94de-4c08-a433-058e62c4456a.png)

![image](https://user-images.githubusercontent.com/1313428/230787089-701234bb-97c3-4d7a-9551-c515b90b19a5.png)

![image](https://user-images.githubusercontent.com/1313428/230787150-857682c6-e9a8-48d7-9582-370ac84c11a1.png)

there is global variable wk and it s not defined !!

**Comment by eyalk11** [comment]
Yeh, better to add 
```
wk=require('which-key')
```
in the example.
