### ISSUE TITLE
ERROR： API Error

### ISSUE THREAD

**Issue by duanyuluo** [jackMort/ChatGPT.nvim#145]
:ChatGPT cmd, then raise a error as below:
Error executing vim.schedule lua callback: Vim:E474: Attempt to decode a blank string
stack traceback:
        [C]: in function 'json_decode'
        .../.local/share/nvim/lazy/ChatGPT.nvim/lua/chatgpt/api.lua:68: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

PS. key has been config in environment.

**Comment by mdomurad** [comment]
Same issue. Any hints how to fix it?

**Comment by mdomurad** [comment]
For anyone having the same issue with gpg encrypted key. For me it was wrong api_key_cmd definition. If you are on Windows it should be:

api_key_cmd = "gpg --decrypt path_to_your_key.gpg 2>/null",

so without dev.

**Comment by Yousuf28** [comment]
here is my init.lua setup for ChatGPT.  I am using windows. this still does not work. It does not give an error but I don't get any response back. If I put OPENAI_API_KEY in my system variable all works fine though. 
Anyone know how to solve this?
```
{
  "jackMort/ChatGPT.nvim",
    event = "VeryLazy",
    config = function()
      require("chatgpt").setup({

    api_key_cmd = "gpg --decrypt ~/nvim_openai_key.txt.gpg 2>/null",

popup_layout = {
      default = "right",
      -- center = {
      --   width = "50%",
      --   height = "50%",
      -- },
      right = {
        width = "30%",
        width_settings_open = "50%",
      },
    },
  openai_edit_params = {
      model = "gpt-3.5-turbo",
      temperature = 0,
      top_p = 1,
      n = 1,
    },

      })
    end,
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    }
},
```

**Comment by SvenKethz** [comment]
`2>/null` should be `/dev/null`, shouldn't it?

**Comment by bruteforks** [comment]
I can't remember how I fixed this error but it started working after I set it up like this in my packer plugins file, or wherever you setup your plugins. You of course need to create the key as specified in docs. Cheers! Love the plugin!!!

```js
use({
  "jackMort/ChatGPT.nvim",
  config = function()
    require("chatgpt").setup({
      api_key_cmd = "gpg --decrypt ~/secret.txt.gpg 2>/dev/null",
    })
  end,
  requires = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
  },
})
```

also a bonus for whichkey user's since I'm posting code:
```lua
c = {
  name = "ChatGPT",
  c = { "<cmd>ChatGPT<CR>", "ChatGPT" },
  e = { "<cmd>ChatGPTEditWithInstruction<CR>", "Edit with instruction" },
  g = { "<cmd>ChatGPTRun grammar_correction<CR>", "Grammar Correction" },
  t = { "<cmd>ChatGPTRun translate<CR>", "Translate" },
  k = { "<cmd>ChatGPTRun keywords<CR>", "Keywords" },
  d = { "<cmd>ChatGPTRun docstring<CR>", "Docstring" },
  a = { "<cmd>ChatGPTRun add_tests<CR>", "Add Tests" },
  o = { "<cmd>ChatGPTRun optimize_code<CR>", "Optimize Code" },
  s = { "<cmd>ChatGPTRun summarize<CR>", "Summarize" },
  f = { "<cmd>ChatGPTRun fix_bugs<CR>", "Fix Bugs" },
  x = { "<cmd>ChatGPTRun explain_code<CR>", "Explain Code" },
  r = { "<cmd>ChatGPTRun roxygen_edit<CR>", "Roxygen Edit" },
  l = { "<cmd>ChatGPTRun code_readability_analysis<CR>", "Code Readability Analysis" },Analysis" },
```

**Comment by ramneeksokhi** [comment]
hey i have entered my key .. but i keep getting the message "Incorrect API key provided:" . i tried pasting it directly in  "api_key_cmd =". anyone how to solve this?
