### ISSUE TITLE
Out of bounds chats

### ISSUE THREAD

**Issue by eyalk11** [jackMort/ChatGPT.nvim#151]
Sometimes the reply by chatgpt out of bounds of frame, and I can't get to it.

![image](https://user-images.githubusercontent.com/72234965/231318490-9bacf2b3-9382-42cb-8dfb-e48d91ff5154.png)

In the case, the frame ends prematurely and scrolling commands doesn't seem to have an effect.

**Comment by eyalk11** [comment]
```{"id":"chatcmpl-","usage":{"total_tokens":1656,"prompt_tokens":1356,"completion_tokens":300},"object":"chat.completion","model":"gpt-3.5-turbo-0301","choices":[{"finish_reason":"length","message":{"role":"assistant","content":"The LoadBaseInserts function loads the inserts cache file and trims it if necessary. It uses the pickle module to load the inserts dictionary from the cache file. If the load time is greater than the maximum load time or if the function is called with the pr argument set to 1, it trims the inserts dictionary by removing any entries that are older than the maximum time span. The function also keeps track of the number of inserts per buffer in the last 20 seconds and pauses insert tracking if the number exceeds a certain threshold. \n\nThe returninsertsforbufn function returns a dictionary of inserts for a given buffer name. It filters out empty or non-ASCII inserts and can break up inserts into individual lines if the breaklines argument is set to True. \n\nThe SaveLastInsert function is called whenever an insert is made in normal mode. It calls the AddInsert function to add the insert to the inserts dictionary. \n\nThe SaveLastCopy function is called whenever a yank operation is performed. It calls the AddInsert function to add the yanked text to the inserts dictionary. \n\nThe AddInsert function calls the AddInsertInternal function to add the insert to the inserts dictionary. It first checks if the number of inserts in the last 20 seconds exceeds a certain threshold and pauses insert tracking if it does. It then converts any backspaces in the insert to newlines and calls the insertfunc function to add the insert to the inserts dictionary. \n\nThe CleanIns function clears the"},"index":0}],"created":1681770226}```

I added log to the engine (will be pull request) , and see "finish_reason":"length" from the api. Maybe out of scope question, but is there a way to deal with it? And why is that?

**Comment by eyalk11** [comment]
Apperently, I guess that I had to understand the token mechanism to understand this bug. 
However, I still find it a worthy challenge, to try to make chatgpt do changes greater than allowed by maximal tokens. That is of course requires consecutive requests to chatgpt like probably mckaywrigley does. 
See:

```
"id": "56ceeaf2-9946-4349-a190-e994942ddcdc",
      "name": "Generate Code",
      "description": "Generates code given a description.",
      "content": "I need code that does the following:\n{{description}}\n\nGenerate the code for me.\n\nRespond as a markdown code block.",
      "model": {
        "id": "gpt-3.5-turbo",
        "name": "GPT-3.5",
        "maxLength": 12000,
        "tokenLimit": 4000
      },
      "folderId": "6eea5390-b971-4fd4-9a17-3bb60f657b9d"
    },
```
https://github.com/mckaywrigley/prompts/blob/main/prompts.json 

So, there is some way to fetch the code in parts.

**Comment by jackMort** [comment]
please reopen if issue still exists in newest version
