### ISSUE TITLE
Not sure how to get this setup sorry

### ISSUE THREAD

**Issue by michael-odonovan** [jackMort/ChatGPT.nvim#154]
Appreciate your help.
I have this in my plugins.lua:
```
  use({
    "jackMort/ChatGPT.nvim",
      config = function()
        require("chatgpt").setup({
        })
      end,
      requires = {
        "MunifTanjim/nui.nvim",
        "nvim-lua/plenary.nvim",
        "nvim-telescope/telescope.nvim"
      }
  })
```

Then in an .env file in the root of my config:
```$OPENAI_API_KEY = "key-i-got-from-open-ai"```

How do I point the setup function to this OPENAI env key variable?
If you help me get it running I will contribute to docs to help others.
thanks

**Comment by mquhuy** [comment]
The following works for me:
- Add source ${path to .env file} into your .bashrc/.zshrc
- Run nvim with OPENAI_API_KEY=${OPENAI_API_KEY} nvim

**Comment by eyalk11** [comment]
I use simply 
```
require("chatgpt").setup()
```
And installed it with plug.
