### ISSUE TITLE
bigger `ChatGPTRun explain_code` explanation float window?

### ISSUE THREAD

**Issue by bryant-video** [jackMort/ChatGPT.nvim#156]
After doing `ChatGPTRun explain_code`, the explanation float window is too small, is there any way to make it bigger?

**Comment by Mephistophillis** [comment]
I have the same problem. I want to modify the styles of the nui.popup that appears when the "display" strategy action is executed.
But it seems that it is not overwritable in https://github.com/jackMort/ChatGPT.nvim/blob/main/lua/chatgpt/flows/actions/chat/init.lua#L93
