### ISSUE TITLE
C-Enter in prompt will not submit 

### ISSUE THREAD

**Issue by ljseng** [jackMort/ChatGPT.nvim#170]
C-Enter in prompt will not submit. It will enter a new line in the prompt.

I am using Packer as my plugin manager. 

```
    -- chatgpt
    use {
        'jackMort/ChatGPT.nvim',
        config = function() require("chatgpt").setup() end,
        requires = {
            "MunifTanjim/nui.nvim",
            "nvim-lua/plenary.nvim",
            "nvim-telescope/telescope.nvim"
        }
    }
```

below is list of plugin i use.
ChatGPT.nvim
LuaSnip
aerial.nvim
barbar.nvim
cmp-nvim-lsp
cmp_luasnip
everforest
friendly-snippets
gitsigns.nvim
lualine.nvim
marks.nvim
mason-lspconfig.nvim
mason.nvim
nui.nvim
nvim-autopairs
nvim-cmp
nvim-comment
nvim-lspconfig
nvim-notify
nvim-tree.lua
nvim-treesitter
nvim-web-devicons
nvim_context_vt
packer.nvim
plenary.nvim
telescope.nvim
toggleterm.nvim
trouble.nvim

i am using [ShellGPT](https://github.com/TheR1D/shell_gpt) and it is working my zsh. thus, pretty sure my token is valid. just not sure why C-Enter is not submitting the prompt.

![image](https://user-images.githubusercontent.com/16687151/234174178-8761d424-ae42-4c81-9c65-1681b70874d6.png)

**Comment by PGimenez** [comment]
same here with lazy, I just installed and C-Enter doesn't submit

**Comment by comiluv** [comment]
What's the OS and terminal do you use?

**Comment by ZacxDev** [comment]
i am also facing this issue, remapping the submit key also doesn't seem to work unless I am doing something wrong.

```
"jackMort/ChatGPT.nvim",
  config = function()
    require("chatgpt").setup({
      chat = {
        prompt_input = {
          submit = "<C-g>"
        }
      }
    })
  end,
  requires = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim"
  }
})

```

**Comment by bx2** [comment]
@ljseng a duplicate? https://github.com/jackMort/ChatGPT.nvim/issues/105

**Comment by tinnguyen189atnos** [comment]
This is worked for me.
```lua
	chatgpt.setup({
		popup_input = {
			submit = "<CR>"
		}
	})
```

> i am also facing this issue, remapping the submit key also doesn't seem to work unless I am doing something wrong.
> 
> ```
> "jackMort/ChatGPT.nvim",
>   config = function()
>     require("chatgpt").setup({
>       chat = {
>         prompt_input = {
>           submit = "<C-g>"
>         }
>       }
>     })
>   end,
>   requires = {
>     "MunifTanjim/nui.nvim",
>     "nvim-lua/plenary.nvim",
>     "nvim-telescope/telescope.nvim"
>   }
> })
> ```

**Comment by rogerkk** [comment]
@tinnguyen189atnos That means you are no longer able to do multiline prompts, right?

But I think the reason this works for @tinnguyen189atnos is that he is setting `popup_input`, not `prompt_input` like @ZacxDev mentions trying. Doing _that_, I was able to remap submit to `C-s` as a workaround:

```
	chatgpt.setup({
		popup_input = {
			submit = "<C-s>"
		}
	})
```

**Comment by rogerkk** [comment]
But I think the reason this works for @tinnguyen189atnos is that he is setting `popup_input`, not `prompt_input` like @ZacxDev mentions trying. Doing _that_, I was able to remap submit to CTRL+s as a workaround:

```lua
chatgpt.setup({
  popup_input = {
    submit = "<C-s>"
  }
})
```

**Comment by devnoot** [comment]
I was having this issue and it turned out to be how Windows terminal was handling `Ctrl+Enter`. I suspect this might be the issue for other terminals as well.

**Comment by ljseng** [comment]
@rogerkk @tinnguyen189atnos thanks very much! following remap works for me.

```lua
	chatgpt.setup({
		popup_input = {
			submit = "<CR>"
		}
	})
```
and @rogerkk yes you can still do multiline prompts. <C-Enter> will enter newline character in windows terminal.

> This is worked for me.
> 
> ```lua
> 	chatgpt.setup({
> 		popup_input = {
> 			submit = "<CR>"
> 		}
> 	})
> ```
> 
> > i am also facing this issue, remapping the submit key also doesn't seem to work unless I am doing something wrong.
> > ```
> > "jackMort/ChatGPT.nvim",
> >   config = function()
> >     require("chatgpt").setup({
> >       chat = {
> >         prompt_input = {
> >           submit = "<C-g>"
> >         }
> >       }
> >     })
> >   end,
> >   requires = {
> >     "MunifTanjim/nui.nvim",
> >     "nvim-lua/plenary.nvim",
> >     "nvim-telescope/telescope.nvim"
> >   }
> > })
> > ```



> > ```lua
> > 	chatgpt.setup({
> > 		popup_input = {
> > 			submit = "<CR>"
> > 		}
> > 	})
> > ```
> 
> @tinnguyen189atnos That means you are no longer able to do multiline prompts, right?
