### ISSUE TITLE
Can't submit prompt

### ISSUE THREAD

**Issue by mlp1802** [jackMort/ChatGPT.nvim#175]
Pressing enter or ctrl+enter just creates a new line..

**Comment by shutils** [comment]
Hi @mlp1802 ! I noticed that this issue is quite similar to issue #170  that has already been reported. It might be worth checking out that issue to see if it addresses your concern. Let's keep the discussion consolidated to avoid duplicates. Thank you!

**Comment by mlp1802** [comment]
Ill close it, thanks
