### ISSUE TITLE
Showing settings in chat and submitting edit-with-instructions raises typing errors

### ISSUE THREAD

**Issue by sum-rock** [jackMort/ChatGPT.nvim#176]
### Issues

- Unable to open the settings panel on chat prompt window. Raises error.
- Unable to submit prompt during edit-with-instructions. Raises error.

### Reproduction

I'm using a Nix flake to manage neovim configurations. This shouldn't matter for this issue though. You can find my `ChatGPT.lua` configuration [here](https://github.com/sum-rock/just-sum-nix/blob/master/homes/modules/neovim/lua/my_chatgpt.lua) (that part's written in Lua). 

When I open the chat window and press `<c-o>`, I receive the error state shown below.
```
E5108: Error executing lua: ...NeovimPackages/start/chatgpt-nvim/lua/chatgpt/module.lua:218: Expected Lua number
stack traceback:
        [C]: in function 'nvim_set_current_win'
        ...NeovimPackages/start/chatgpt-nvim/lua/chatgpt/module.lua:218: in function <...NeovimPackages/start/chatgpt-nvim/lua/chatgpt/module.lua:199>
Press ENTER or type command to continue
```

When I open the edit-with-instructions window and press `<c-s>` (I've remapped this to be able to submit as advised by other issues here), I receive the error state shown below:
```
E5108: Error executing lua: ...imPackages/start/chatgpt-nvim/lua/chatgpt/code_edits.lua:132: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_get_lines'
        ...imPackages/start/chatgpt-nvim/lua/chatgpt/code_edits.lua:132: in function <...imPackages/start/chatgpt-nvim/lua/chatgpt/code_edits.lua:130>
Press ENTER or type command to continue
```

### Debugging efforts

You can see my list of plugins [here](https://github.com/sum-rock/just-sum-nix/blob/c51f3a97e916ecf61997cd8e9b468e1427b70f26/homes/modules/neovim/default.nix#L60). I've uninstalled bufferline in to check for incompatibility. This didn't change anything. 

I've cloned this `ChatGPT.nvim` and did some debugging on the chat settings panel specifically. What I've noticed here is that the instantiation of the `settings_panel` in `modules` [here](https://github.com/jackMort/ChatGPT.nvim/blob/cd060d2dd9abb72e24d7921cdbcf3f57cc720105/lua/chatgpt/module.lua#L67) is either returning a `nil` value or an empty class (sorry if my terms are wrong, I'm not super familiar with Lua!). My mind first went to some async issues so I wrapped the settings toggle in an async call to force await before referencing the settings panel but my effort either didn't work or this isn't the issue. 

### HELP!

I'd be happy to help fix this issue if its effecting more people but I didn't see an issue from anyone else which leads me to think that maybe I've done something dumb. Is anyone else experiencing this problem!?

**Comment by jackMort** [comment]
please reopen if issue still exists in newest version
