### ISSUE TITLE
Prompt submit broken

### ISSUE THREAD

**Issue by scottarthur** [jackMort/ChatGPT.nvim#179]
Here's my nvim version:

```
> nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

I've got a stripped down init.lua:

```
require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  use({"jackMort/ChatGPT.nvim",
    config = function()
      require("chatgpt").setup()
    end,
    requires = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    }
  })

end)
```

Problem is this: Whenever I open any `:ChatGPT*` command, the default keybinding of `<C-Enter>` does not submit the prompt, it instead creates a newline in the prompt field.  When this happens, previous output is repeated in the response window.  This happens both in INSERT or NORMAL mode.  I've tried specifying other values for the submit keybinding in `setup()` but nothing seems to work.  All other command keybindings (new session, select session, delete session) work as intended.  I've ruled out problems with my token/ChatGPT connection because opening up a `:ChatGPTActAs` successfully queries the API and prints the response from the initial prompt. 

Thanks!

**Comment by vitosans** [comment]
👍

**Comment by jackMort** [comment]
I added option to submit by enter in normal mode, please try if it solves this issue for you

**Comment by ljseng** [comment]
hi @scottarthur see #170

**Comment by scottarthur** [comment]
Ah yeah, this is a dup of #170, closing. Thanks!
