### ISSUE TITLE
API ERROR: We could not parse the JSON body of your request

### ISSUE THREAD

**Issue by zpl-zak** [jackMort/ChatGPT.nvim#184]
Hi, I am using
NVIM v0.9.0
LuaJIT 2.1.0-beta3
Windows 11
Windows Terminal with MSYS2's bash shell

Whenever I execute any ChatGPT query I receive the following error:
```
ERROR: API Error

 // API ERROR: We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP
library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble
figuring out how to fix this, please contact us through our help center at help.openai.com.)
```

my API key is set in env and freshly created as well.

**Comment by comiluv** [comment]
I was having a similar problem. In my testing, Windows was adding random(?) whitespace at the end of the key string captured from reading environment variables and gnupg decryption. I'll make a PR that fixes this issue.
