### ISSUE TITLE
Can't get it to work with the GPT-4 model

### ISSUE THREAD

**Issue by Vanclief** [jackMort/ChatGPT.nvim#186]
First of all thanks for the plugin @jackMort, its very cool.

So I got access to the GPT-4 API, so I am trying to enable it in the plugin but I am not being able to. I tried by updating the config:

```
  openai_params = {
    model = "gpt-4",

  },
```

And by just editing it directly on the chat settings as stated in here https://github.com/jackMort/ChatGPT.nvim/issues/104#issuecomment-1499509201

But neither option worked for me

![image](https://user-images.githubusercontent.com/13844339/236641546-574a7bf8-800e-4ba3-8b9a-a64293f80d47.png)

**Comment by eyalk11** [comment]
You take chatgpt word for it? It is probably working

**Comment by Vanclief** [comment]
Interesting, probably true. I checked in the webapp Chat version and it was returning the correct version. But in the playground it doesn't return the correct version.

**Comment by jackMort** [comment]
As openai says, it's limited beta, there's wait-list https://openai.com/waitlist/gpt-4-api to join

**Comment by wstewarttennes** [comment]
@jackMort I have access to the gpt-4 plugin (i think we all do as of today) but still seeing this same issue after adding "gpt-4" to my config

**Comment by Vanclief** [comment]
@wstewarttennes I think that its actually gpt-4 even if the response to the prompt its different. Seems that when using the Chat GPT UI there are some extra embedings than when calling it directly from the API or from the playground.

**Comment by wstewarttennes** [comment]
@Vanclief thanks for the info -- how do you determine if it's using the correct one? the documentation here states it uses 3.5-turbo so i was worried it was hard coded

**Comment by Ryel** [comment]
> @Vanclief thanks for the info -- how do you determine if it's using the correct one? the documentation here states it uses 3.5-turbo so i was worried it was hard coded

You can double check which model you're using from the Daily Usage Breakdown section here: https://platform.openai.com/account/usage

![Screenshot 2023-07-13 at 1 34 38 PM](https://github.com/jackMort/ChatGPT.nvim/assets/4242005/9be64800-e366-41a6-9ab5-e17b2bceba5e)
