### ISSUE TITLE
Failing Setup

### ISSUE THREAD

**Issue by JustinStitt** [jackMort/ChatGPT.nvim#196]
I am attempting to install via Lazy (in LunarVim) but am receiving the following error message:

![image](https://github.com/jackMort/ChatGPT.nvim/assets/24460581/db3f8b56-60ee-4113-8809-721c95d57f12)

as I am just copy/pasting the documentation I am not sure what could be awry here.

Any help would be greatly appreciated.

> LunarVim v1.3 NVIM v0.9

**Comment by JustinStitt** [comment]
Here's the lua
```lua
  {
    "jackMort/ChatGPT.nvim",
    event = "VeryLazy",
    config = function()
      require("chatgpt").setup()
    end,
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    },
  },
```

**Comment by JustinStitt** [comment]
Fixed it by hard coding my API key into the plugin's Api setup.

**Comment by alifanov** [comment]
I used export OPENAI_API_KEY=... before starting nvim
