### ISSUE TITLE
Transparent background black shadow hlgroup?

### ISSUE THREAD

**Issue by mattiasbonte** [jackMort/ChatGPT.nvim#2]
Hi, 

I was trying out your plugin but stumbled upon this (highlight?) issue. The background appears black. It looks as if it's a shadow.. I might be wrong though. I'm not familiar with styling/hlgroup manipulation.

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/65280774/207743468-5f11844d-b576-4360-8b6e-9e8d3242c07c.png">

Would you have any idea what might be causing this and how I could fix it? I'm using the [catpuccin colorscheme](https://github.com/catppuccin/nvim).

Thank you for your time.

**Comment by jackMort** [comment]
What terminal emulator are you using?

**Comment by mattiasbonte** [comment]
I'm using wezterm. But I don't think it has much to do with the emulator. I tried Kitty and Alacritty and they also show the same background. I tried it with an empty config and tried to change the highlight groups but without success. To me it looks like it's a shadow. Could it be that `nui` is producing this?

**Comment by MunifTanjim** [comment]
@jackMort can you try setting `grow = 1` instead of `size = "90%"` here?

https://github.com/jackMort/ChatGPT.nvim/blob/d7703bd2453a1599367b3fd7df109601ee3783e4/lua/chatgpt/module.lua#L43

**Comment by jackMort** [comment]
Thanks a lot, that's something I've been looking for 🙏

**Comment by Leo310** [comment]
Problem still exists on my side. still getting that shadow

**Comment by jackMort** [comment]
Could you please share the screenshot?

**Comment by Leo310** [comment]
using alacitty:
![image](https://user-images.githubusercontent.com/48623649/208722549-18646a5d-3990-40c2-b756-7d90d23acc35.png)

**Comment by mattiasbonte** [comment]
Can confirm, problem still exists.

**Comment by vladovidiu** [comment]
Can confirm I have the same issue.

**Comment by MunifTanjim** [comment]
Can you check if the issue still exists with https://github.com/MunifTanjim/nui.nvim/issues/230?

**Comment by jackMort** [comment]
I had same issue with different colorschemes, but it looks like it was solved, great job!

**Comment by Leo310** [comment]
yeah seems to be working
