### ISSUE TITLE
Model's maximum context length

### ISSUE THREAD

**Issue by lf-araujo** [jackMort/ChatGPT.nvim#201]
Hi all, 

This must be a simple issue, but I can't use the chat.gpt window as it reached the maximum length. 

- How to reset the conversation?

![image](https://github.com/jackMort/ChatGPT.nvim/assets/10139950/7ef7cf57-3a73-4541-b681-76bba6d2e8a6)

**Comment by jackMort** [comment]
You can manage multiple sessions, Ctrl+n to open new, Ctr+o to toggle sessions panel

**Comment by lf-araujo** [comment]
Thanks, I couldn't find this info.
