### ISSUE TITLE
Cannot install with Packer

### ISSUE THREAD

**Issue by MirceaDumitrescu** [jackMort/ChatGPT.nvim#205]
I have lots of other plugins, similarlly installed.

At the moment tried adding it with the simple clean use method. :PackerSync installed it but upon restart, getting this error. Tried several ideas of fixing it but simply doesn't work.

I believe the initial image error below is caused because api_key_cmd was missing. Perhaps error can be improved? However, i believe i have API key error, again, errors are not very descriptive or conclusive. It tooke me 6 attempts to receive a conclusive error message in the prompt.

Please check images below.

For context, using Ubuntu in WSL.

![image](https://github.com/jackMort/ChatGPT.nvim/assets/16415899/83a42e25-c68b-409e-a9df-c018e1473f91)

![image](https://github.com/jackMort/ChatGPT.nvim/assets/16415899/b6d7df5d-b26a-4f01-910f-1ebd320654e7)

![image](https://github.com/jackMort/ChatGPT.nvim/assets/16415899/4716de1d-232e-4d6d-a8d6-77ac8b55ca2e)

![image](https://github.com/jackMort/ChatGPT.nvim/assets/16415899/8749fbe1-380e-4d19-bd26-4b7aa7352aae)

**Comment by d3287t328** [comment]
I installed it successfully with Packer today (I haven't gotten it working yet which is another problem). Have you asked chatgpt for some potential solutions?

**Comment by jackMort** [comment]
try <ctr-n> to create new session, this message may came from history
