### ISSUE TITLE
Error when trying to use the Run command

### ISSUE THREAD

**Issue by Tobi-De** [jackMort/ChatGPT.nvim#207]
![image](https://github.com/jackMort/ChatGPT.nvim/assets/40334729/0c8513f0-1a3f-42d0-ab62-40692b1fcc64)

No idea what is happening, I'm pretty new to vim and neovim, If there is any command I can run to get logs or more details to help fix this, please let me know. All the other commands are working flawlessly, I'm using lazy.nvim as my package manager, and this is my config:

```lua
  {
    "jackMort/ChatGPT.nvim",
    event = "VeryLazy",
    config = function()
      require("chatgpt").setup({
        api_key_cmd = "pass show nvim_chatgpt_key",
        predefined_chat_gpt_prompts = "https://raw.githubusercontent.com/Tobi-De/awesome-chatgpt-prompts/main/prompts.csv",

      })
    end,
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    }
  }
```

**Comment by George-Yanev** [comment]
I have the same effect if I run `:ChatGPTRun` without a parameter.

You should see specify  for example `:ChatGPTRun add_tests`


![image](https://github.com/jackMort/ChatGPT.nvim/assets/478709/911254d1-ebd7-4c10-b20d-86f1e92a3dc2)
