### ISSUE TITLE
How to use with Azure OpenAI

### ISSUE THREAD

**Issue by juliano-barbosa** [jackMort/ChatGPT.nvim#212]
is possible use this with azure openAI ?

curl:

curl https://`<your-resource>`.openai.azure.com/openai/deployments/`<your-deploy>`/completions?api-version=2022-12-01 \
  -H "Content-Type: application/json" \
  -H "api-key: YOUR_API_KEY" \
  -d '{
  "prompt": "",
  "max_tokens": 100,
  "temperature": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "top_p": 0.5,
  "stop": null
}'

**Comment by lianghx-319** [comment]
If the apis are compatible, I think this pr can help you https://github.com/jackMort/ChatGPT.nvim/pull/210
