### ISSUE TITLE
lua errors on ChatGPTRun

### ISSUE THREAD

**Issue by SvenKethz** [jackMort/ChatGPT.nvim#214]
Thanks a lot for this plugin! 

The command ChatGPTRun isn't working on my system:
Linux Mint 21.1 x86_64
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

Whenever I call it, I get the following errors:

`Error executing Lua callback: ...vim/lazy/ChatGPT.nvim/lua/chatgpt/flows/actions/init.lua:59: attempt to index local 'item' (a nil v
alue)
stack traceback:
        ...vim/lazy/ChatGPT.nvim/lua/chatgpt/flows/actions/init.lua:59: in function 'run_action'
        ...sven/.local/share/nvim/lazy/ChatGPT.nvim/lua/chatgpt.lua:46: in function 'run_action'
        ...n/.local/share/nvim/lazy/ChatGPT.nvim/plugin/chatgpt.lua:14: in function <...n/.local/share/nvim/lazy/ChatGPT.nvim/plugin
/chatgpt.lua:13>
`
Don't know if it is a bug - how can I help to track it down?

**Comment by stelgenhof** [comment]
I'm facing the same issue/error. All the other commands work fine though.

My setup:
Arch Linux 6.3.7-arch1-1
NVIM 0.9.1

**Comment by stelgenhof** [comment]
Ah, just noticed why this is happening: When you just call `ChatGPTRun` without any arguments, this error pops up. If, however, you type a space and then <TAB>, you will be presented with the list of possible commands.

**Comment by SvenKethz** [comment]
> Ah, just noticed why this is happening: When you just call `ChatGPTRun` without any arguments, this error pops up. If, however, you type `ChatGPRun` followed by a space and then a , you will be presented with the selection list of possible commands.

Thanks a lot!!! That solves it.

**Comment by lelouvincx** [comment]
Thanks.
