### ISSUE TITLE
Could not run :ChatGPT

### ISSUE THREAD

**Issue by Gorgeous-Patrick** [jackMort/ChatGPT.nvim#216]
Hi this is my error output:

Error executing Lua callback: ...acker/start/ChatGPT.nvim/lua/chatgpt/flows/chat/base.lua:47: attempt to index field 'popup_layout' (a nil value)
stack traceback:
        ...acker/start/ChatGPT.nvim/lua/chatgpt/flows/chat/base.lua:47: in function 'init'
        ...packer/start/ChatGPT.nvim/lua/chatgpt/common/classes.lua:88: in function 'new'
        ...acker/start/ChatGPT.nvim/lua/chatgpt/flows/chat/init.lua:13: in function 'open_chat'
        ...nvim/site/pack/packer/start/ChatGPT.nvim/lua/chatgpt.lua:34: in function 'openChat'
        ...m/site/pack/packer/start/ChatGPT.nvim/plugin/chatgpt.lua:2: in function <...m/site/pack/packer/start/ChatGPT.nvim/plugin/chatgpt.lua:1>

This is my lua packer config:
        use({
          "jackMort/ChatGPT.nvim",
            config = function()
                require("chatgpt").setup()
            end,
            requires = {
              "MunifTanjim/nui.nvim",
              "nvim-lua/plenary.nvim",
              "nvim-telescope/telescope.nvim"
            }
        })

**Comment by Gorgeous-Patrick** [comment]
Solved by :PackerUpdate

**Comment by huangyingw** [comment]
I have exactly the same issue, but PackerUpdate didn't help...

**Comment by huangyingw** [comment]
> I have exactly the same issue, but PackerUpdate didn't help...

sorry, maybe after cleaning my nvim plugins, or maybe PackerSync help, to make it work
