### ISSUE TITLE
api key error

### ISSUE THREAD

**Issue by azinsharaf** [jackMort/ChatGPT.nvim#222]
I am using a paid plan and has created an env var `OPENAI_API_KEY` submitting any query returns "incorrect api key provided'. The API key in the screenshot below doesn't match with the one i have as env var.

![image](https://github.com/jackMort/ChatGPT.nvim/assets/10101468/a86823be-688b-4117-800b-b523502d8c18)

**Comment by jackMort** [comment]
Make sure it's correctly exported, open terminal and run: echo $OPENAI_API_KEY to validate

**Comment by azinsharaf** [comment]
using it on Windows. 
dir envs: command returns the correct env variable value.

**Comment by azinsharaf** [comment]
it seems removing chatgpt.nvim folder in nvim-data parent folder and then installing it again fixed the issue.
