### ISSUE TITLE
current quota exceeded

### ISSUE THREAD

**Issue by azinsharaf** [jackMort/ChatGPT.nvim#224]
I have a paid subscription ($20 per month), created a api key via `https://platform.openai.com/account/api-keys`, created a `OPENAI_API_KEY` environment variable in Windows 11 with the api key value. 
I am getting the following error when running `:ChatGPT`:
`You exceeded your current quota, please check your plan and billing details.`

**Comment by miguelmoraperea** [comment]
@azinsharaf Try creating a new session <C-n>, that solved the issue for me.

**Comment by azinsharaf** [comment]
@miguelmoraperea  creating a new session deletes the error message but it happens again after submitting a new query.

**Comment by miguelmoraperea** [comment]
@azinsharaf In that case, I think you might need to set up a billing account with ChatGPT API. "ChatGPT and ChatGPT Plus subscriptions are billed separately. The API has its own pricing, which can be found at https://openai.com/pricing. The ChatGPT Plus subscription covers usage on chat.openai.com only..." according to their website.

**Comment by azinsharaf** [comment]
i re-entered my credit card info and it started to work.
