### ISSUE TITLE
[bug] bad completion for partial code

### ISSUE THREAD

**Issue by kaiphat** [jackMort/ChatGPT.nvim#231]
![image](https://github.com/jackMort/ChatGPT.nvim/assets/53742299/318f3126-fbb2-468c-afbe-80baa378bd62)
![image](https://github.com/jackMort/ChatGPT.nvim/assets/53742299/70fa5a59-e703-4382-b15a-f71a5a190683)
![image](https://github.com/jackMort/ChatGPT.nvim/assets/53742299/e529e073-f0f2-4265-83e6-1b3ad278d646)
Strange `//` chars
Press enter
![image](https://github.com/jackMort/ChatGPT.nvim/assets/53742299/6a22cffe-3342-4a74-86c0-79132c34d104)

**Comment by jackMort** [comment]
`// `was returned by openai api, something like this may happen depending of context
