### ISSUE TITLE
[bug] replace code for translate action

### ISSUE THREAD

**Issue by kaiphat** [jackMort/ChatGPT.nvim#232]
Before: 
![image](https://github.com/jackMort/ChatGPT.nvim/assets/53742299/030ab020-4a81-47c4-9830-5e62a4aadfdb)
![image](https://github.com/jackMort/ChatGPT.nvim/assets/53742299/cdb89b0a-1142-476a-b74f-1b508f40677f)
![image](https://github.com/jackMort/ChatGPT.nvim/assets/53742299/04a8989e-d6f7-4b57-b5b9-ffd1b63c2f02)
![image](https://github.com/jackMort/ChatGPT.nvim/assets/53742299/8dadd17f-18f5-4727-b22e-622edba9e6c1)
Result
![image](https://github.com/jackMort/ChatGPT.nvim/assets/53742299/f3b69cc4-de5c-4bd8-a10b-eff6f464784d)

**Comment by jackMort** [comment]
translate expects additional parameter eg. `ChatGPTRun translate en`
