### ISSUE TITLE
Failed to run `config` for ChatGPT.nvim - echo: Executable not found

### ISSUE THREAD

**Issue by XenoCode54** [jackMort/ChatGPT.nvim#239]
I'm getting this error, please help!

Failed to run `config` for ChatGPT.nvim

...ta/Local/nvim-data/lazy/plenary.nvim/lua/plenary/job.lua:106: echo: Executable not found
stack traceback:
	...ta/Local/nvim-data/lazy/plenary.nvim/lua/plenary/job.lua:106: in function 'new'
	...ta/Local/nvim-data/lazy/ChatGPT.nvim/lua/chatgpt/api.lua:158: in function 'loadApiKey'
	...ta/Local/nvim-data/lazy/ChatGPT.nvim/lua/chatgpt/api.lua:176: in function 'setup'
	...ppData/Local/nvim-data/lazy/ChatGPT.nvim/lua/chatgpt.lua:25: in function 'setup'
	C:/Users/Xenon/AppData/Local/nvim/lua/plugins/chatgpt.lua:5: in function 'config'
	.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:354: in function <.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:352>
	[C]: in function 'xpcall'
	...ta/Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/util.lua:110: in function 'try'
	.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:369: in function 'config'
	.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:337: in function '_load'
	.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:184: in function 'load'
	...nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:33: in function <...nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:26>
	[C]: in function 'nvim_exec_autocmds'
	...ta/Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/util.lua:149: in function <...ta/Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/util.lua:144>

# stacktrace:
  - plenary.nvim\lua\plenary\job.lua:106 _in_ **new**
  - ChatGPT.nvim\lua\chatgpt\api.lua:158 _in_ **loadApiKey**
  - ChatGPT.nvim\lua\chatgpt\api.lua:176 _in_ **setup**
  - ChatGPT.nvim\lua\chatgpt.lua:25 _in_ **setup**
  - AppData/Local/nvim/lua/plugins/chatgpt.lua:5 _in_ **config**

**Comment by 56phil** [comment]
I'm getting the same error. How do I install this missing LUA module?

**Comment by Xoffio** [comment]
Same problem here. Using Windows 11. Did you guys have a solutions for it?
