### ISSUE TITLE
Remove OPENAI_API_KEY warning

### ISSUE THREAD

**Issue by ghaerdi** [jackMort/ChatGPT.nvim#245]
I'm using `api_key_cmd` to set my key but I'm getting this warning, is there any way to remove this warning?
![image](https://github.com/jackMort/ChatGPT.nvim/assets/47613233/82a841bd-4fa2-49bd-a509-5d88efcb93f9)

**Comment by KapJ1coH** [comment]
Have you managed to remove it?
