### ISSUE TITLE
attempt to concatenate field 'OPENAI_API_KEY' (a nil value)

### ISSUE THREAD

**Issue by 8veStory** [jackMort/ChatGPT.nvim#250]
Hi!

I'm on Windows 11 attempting to use the `api_key_cmd` with the Onepassword CLI like so:
```lua
-- ChatGPT
require("chatgpt").setup({ -- Requires either ENV, or api_key_cmd to be setup
  api_key_cmd = 'op read "op://Personal/ChatGPT API Key Windows Emacs/credential" --no-newline',
})
```
 I  have confirmed that running the command by itself gets the desired secret in both CMD and pwsh, however it appears I run into the following error anytime I try to use the plugin to contact OPENAI:

[error.webm](https://github.com/jackMort/ChatGPT.nvim/assets/29248979/d1bcc538-2ef9-4142-9e88-31bae4796164)
```lua
  Error  10:45:53 PM msg_show.lua_error Error executing vim.schedule lua callback: ...ta/Local/nvim-data/lazy/ChatGPT.nvim/lua/chatgpt/api.lua:34: attempt to concatenate field 'OPENAI_API_KEY' (a nil value)
stack traceback:
	...ta/Local/nvim-data/lazy/ChatGPT.nvim/lua/chatgpt/api.lua:34: in function 'chat_completions'
	...m-data/lazy/ChatGPT.nvim/lua/chatgpt/flows/chat/base.lua:713: in function 'on_submit'
	.../Local/nvim-data/lazy/ChatGPT.nvim/lua/chatgpt/input.lu
a:72: in function <.../Local/nvim-data/lazy/ChatGPT.nvim/lua/chatgpt/input.lua:60>
```

Thing I have tried:
* Deleting and reinstalling the Plugin using LazyVim -> does not work
* Used the simpler config `api_key_cmd = "cat secret.txt"` where `secret.txt` contained my secret -> does not work
* Simply adding my API key as an ENV variable OPENAI_API_KEY prior to opening neovim -> this works!

It appears that anything I try to do with `api_key_cmd` does not work, but directly setting the `OPENAI_API_KEY` env does indeed work.

**Comment by shakori999** [comment]
how exactly did you do it?
i tried to set the env variable the third option 
but it turns out it didn't work
can you show me where did you write it?

**Comment by jbpros** [comment]
I'm running into the same issue.

**Comment by densefog** [comment]
Had the same issue but noticed the docs mentioned: 

> Note that the api_key_cmd arguments are split by whitespace. If you need whitespace inside an argument (for example to reference a path with spaces), you can wrap it in a separate script.

So I changed the name of my stored credentials in 1password to remove spaces and this worked: 
```
    require("chatgpt").setup {
      api_key_cmd = "op read op://Private/OpenAI_API_Key/password --no-newline",
    }
```

**Comment by jbpros** [comment]
Thanks @densefog, that worked for me too. I initially kept escaped double-quotes around that URI and it was still failing. People, make sure you remove double quotes and spaces.

**Comment by jackMort** [comment]
please reopen if issue still exists in newest version

**Comment by nikitoshina** [comment]
Ran into the same issue, removed spaces and everything worked!
