### ISSUE TITLE
ChatGPTCompleteCode exceeds token limit

### ISSUE THREAD

**Issue by Rouji** [jackMort/ChatGPT.nvim#252]
`:ChatGPTCompleteCode` results in 
```
// API ERROR: This model's maximum context length is 4093 tokens, however you requested 5074 tokens (3026 in your prompt, suffix; 2048 for the completion).
```
...for files longer than about 300~400 lines.
I haven't touched `max_tokens`, so that should be set to 300.

**Comment by jschoolcraft** [comment]
I'm getting a similar issue with just `:ChatGPT` and asking a simple question: "Summarize the book Multipliers"

```
Summarize the book Multipliers
This model's maximum context length is 4097 tokens. However, you requested 4256 tokens (3956 in the messages, 300 in the completion). Please reduce the length of the messages or completion.
```

**Comment by EduardoNeville** [comment]
I've tried the solution posted on #244 (comment) but even after changing my credit card information the issue persists

**Comment by lalitmeeq** [comment]
Facing the same issue with `ChatGPT` command as well. 

Seems like something to do with the model.

**Comment by Thanatermesis** [comment]
Same issue here,

Or maybe the plugin should just get a bunch of (in cursor place) 100 previous lines + 20 next lines, instead of the entire file 🤔

**Comment by MateuszMielniczuk** [comment]
I am also fighting with this issue:
It is using `gpt-3.5-turbo` by default? I tried to change it to `gpt-3.5-turbo-16k` with larger context length, and increase `max_tokens` value over 10000 but, still getting message with max-context length `4093`.

Is there some additional settings to change model for completion?
