### ISSUE TITLE
Where are the model parameters persisted?

### ISSUE THREAD

**Issue by abhitopia** [jackMort/ChatGPT.nvim#255]
Hello,

Once I update the model from within the interface like following then
<img width="339" alt="image" src="https://github.com/jackMort/ChatGPT.nvim/assets/12864026/537c7e3a-9f7e-4d51-a4da-0bdf0f26de9a">

then this value is persisted across multiple invocations of nvim, irrespective of what defaults are set. For example, 

<img width="341" alt="image" src="https://github.com/jackMort/ChatGPT.nvim/assets/12864026/84930eed-e532-4295-840e-525980c627bb">

May I know where is this value persisted?

I want to use gpt-3.5-turbo by default, except occassionally gpt4.

**Comment by h3ndry** [comment]
I am not sure if I understand you correctly but a best way is to set the model in your config

**Comment by skdziwak** [comment]
Those settings are in ~/.chatgpt-chat_completions-params.json
