### ISSUE TITLE
gpt-4 not working for me

### ISSUE THREAD

**Issue by winslowb** [jackMort/ChatGPT.nvim#258]
this very well work and i'm incorrectly doing something.
* i change the model gpt-4 in config.lua and the plugin doesn't work

![image](https://github.com/jackMort/ChatGPT.nvim/assets/71040996/eee14b07-8e37-4627-8948-cce21d2e6193)

**Comment by h3ndry** [comment]
The are required before you can use gpt-4, you must have been pay at least $1 to OpenAI

**Comment by winslowb** [comment]
makes sense. i do have a subscription...

**Comment by jackMort** [comment]
Make sure gpt-4 is available in your plan - I bealive you need to join the waitlist, you can verify that using openai playground
