### ISSUE TITLE
curl: no URL specified

### ISSUE THREAD

**Issue by thaiducdung255** [jackMort/ChatGPT.nvim#265]
Hi, after install the plugin, i can use it normally but, after some questions, i got this error, please help:
![image](https://github.com/jackMort/ChatGPT.nvim/assets/43328993/4f2ab3b5-8d64-42c1-b5f4-86c81295b0c8)

**Comment by hacker-DOM** [comment]
I am encountering this as well. Didn't happen before.
Must have been introduced in a recent commit.

**Comment by Fissium** [comment]
The same error

**Comment by cauliyang** [comment]
same error

**Comment by lfaudreejr** [comment]
After recent update, OPENAI_API_HOST key not set warning started popping up and this curl error as well.

**Comment by Mephistophillis** [comment]
I found the problem:
if OPENAI_API_HOST exists we should fire the callback for create other variables.
Simple example (with duplicate loadApiConfig func)
https://github.com/Mephistophillis/ChatGPT.nvim/commit/f07b3e4009d883bc6dbcb84f4220fa0b702f6345

**Comment by heimann** [comment]
Temporary fix while we wait is to force your plugin manager to load the last working commit (24bcca7). If you're using Lazy.nvim the configuration that would work is:
```
  {
    "jackMort/ChatGPT.nvim",
    event = "VeryLazy",
    commit = "24bcca7",
    config = function()
      require("chatgpt").setup()
    end,
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    },
  },
```

**Comment by minamorl** [comment]
I think this is pretty corner case so reverting seems good for me
