### ISSUE TITLE
Prevent warning "OPENAI_API_HOST environment variable not set" if you want to use the default 

### ISSUE THREAD

**Issue by Allaman** [jackMort/ChatGPT.nvim#267]
As the title suggests, it would be cool if the warning is not displayed when there is no need to change the API host

**Comment by Allaman** [comment]
Maybe related to https://github.com/jackMort/ChatGPT.nvim/issues/265 ?

**Comment by heimann** [comment]
> Maybe related to #265 ?

They are definitely related as the issue starts occurring with that same commit. However, it does seem like a default of "api.openai.com" is passed at least if you don't provide the host, so I don't think that's the cause of the error :(

**Comment by kohane27** [comment]
I'm suddenly having the same error as well.

**Comment by everdom** [comment]
just edit your .bashrc/.zshrc and add:
```shell
export OPENAI_API_HOST="api.openai.com"
```

**Comment by teto** [comment]
I would prefer to avoid adding yet another environment variable OPENAI_API_HOST. How can I achieve the equivalent by setting api_host_cmd ?

**Comment by nfwyst** [comment]
Good, it is OPENAI_API_HOST, and not OPEN_AI_HOST

**Comment by Allaman** [comment]
> just edit your .bashrc/.zshrc and add:
> 
> ```shell
> export OPENAI_API_HOST="api.openai.com"
> ```

Sure, but don't you think that this is redundant? The README states that this variable is
> ... useful if you can't access OpenAI driectly

IMO, a default setting should not need a configuration nor cause a warning.

**Comment by Allaman** [comment]
> I would prefer to avoid adding yet another environment variable OPENAI_API_HOST. How can I achieve the equivalent by setting api_host_cmd ?

@teto Something like this should work `api_host_cmd = "echo -n 'api.openai.com'"`. Adjust to the correct address!
