### ISSUE TITLE
Misleading because this isn't actually using ChatGPT

### ISSUE THREAD

**Issue by transitive-bullshit** [jackMort/ChatGPT.nvim#28]
This will confuse a lot of people because it's called ChatGPT, but it's not actually using ChatGPT.

**Comment by jackMort** [comment]
I agree wrong naming may be confused, that wasn't my intention, It currently using other available models, and when ChatGPT becomes available, I will switch to it. I have also been trying to use the unofficial API at first, but right now it has too many limitations.

**Comment by transitive-bullshit** [comment]
All good 😄 I know first-hand how difficult working w/ the unofficial API can be (https://github.com/transitive-bullshit/chatgpt-api), so I got excited when I saw this repo.
