### ISSUE TITLE
error when editing code

### ISSUE THREAD

**Issue by eyalk11** [jackMort/ChatGPT.nvim#285]
Whenever I try editing mode, I get the following:

`// API ERROR: 'instruction' is a required property`

I use a slightly changed version(with log). Is it familiar?

**Comment by nikbrunner** [comment]
I get the same error when using `edit_with_instructions`

**Comment by ben-wall** [comment]
Same here would love a fix if possible please, this is when using 
```use({
  "jackMort/ChatGPT.nvim",
    config = function()
      require("chatgpt").setup()
    end,
    requires = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    }
})```
and typing something into the input box and pressing enter

**Comment by nicolimo86** [comment]
it happens to me when i summarize some code, then i try to further ask questions in the text box about the code.
If I inspect `:messages` I see this:
`Edit models are deprecated`

**Comment by nicolimo86** [comment]
I figured it out on my side. I had to change the model from `code-davinci-edit-001o` to `gpt-3.5-turbo` for the edit_with_instructions functionality:
I went from this:
```
openai_edit_params = {
      model = "code-davinci-edit-001o",
      temperature = 0,
      top_p = 1,
      n = 1,
    },
```
to this:
```
openai_edit_params = {
      model = "gpt-3.5-turbo",
      temperature = 0,
      top_p = 1,
      n = 1,
    },
```

**Comment by ekaj2** [comment]
Yes and if you already have it configured, try:

<C-o> to open the settings panel and hit enter on the model to change it manually.

**Comment by jackMort** [comment]
please reopen if issue still exists in newest version
