### ISSUE TITLE
popup background color/transparence

### ISSUE THREAD

**Issue by el-og** [jackMort/ChatGPT.nvim#31]
Hey, quick and probably easy question here. How can I change "popup" background for this plugin? Currently it's transparent window, which is not quite usable for me... Any help appreciated, thanks!
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/19407604/208603106-e68d3875-1394-4149-8b1b-3e74ce02f978.png">

**Comment by jackMort** [comment]
Hey, that strange, which colorscheme are you using? could you please try with different one to check if that's the problem?

**Comment by el-og** [comment]
@jackMort thanks for a quick answer. I use `gruvbox`, I have just tried removing colorscheme and it is still transparent 🤷 
![image](https://user-images.githubusercontent.com/19407604/208625506-f16c2938-f060-4b46-b07c-9c4680fe6489.png)

**Comment by jackMort** [comment]
try remove all your custom config for this plugin and try again, basically `winblend` option for manipulating opacity 0 - 100 where 100 is default value and it means that background is solid. I recently removed all winblend settings by default to avoid such problems

**Comment by el-og** [comment]
so I have removed custom config as you suggested for this plugin and now it's empty, however still same issue 😞 also tried manipulating `winblend` values and that didn't do anything
```
lua << EOF
require"chatgpt".setup{
}
EOF
```

**Comment by jackMort** [comment]
@MunifTanjim do you know what may cause it?

**Comment by MunifTanjim** [comment]
What's the output for these commands?

```
:hi Normal
:hi NormalFloat
:hi FloatBorder
```

With the default config, it looks like this for me:

![image](https://user-images.githubusercontent.com/8050659/208644488-4d941c56-19c1-483f-8cc9-672c732928d7.png)

**Comment by MunifTanjim** [comment]
With slightly tweaked config:

```lua
    chat_window = {
      filetype = "chatgpt",
      border = {
        style = "rounded",
        text = {
          top = " ChatGPT ",
        },
      },
      win_options = {
        winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
      }
    },
    chat_input = {
      prompt = "  ",
      border = {
        style = "rounded",
        text = {
          top_align = "center",
          top = " Prompt ",
        },
      },
      win_options = {
        winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
      }
    },
```

It looks like this:

![image](https://user-images.githubusercontent.com/8050659/208644760-7c963bde-2a70-48f4-8f6c-97fa18ecc467.png)

**Comment by el-og** [comment]
This is output I get (below) and with your tweaked config same UI output 😞 

I have also found `highlight Normal guibg=none` in my vimrc, however removing that didn't impact anything as well 🤷 

```
Normal    xxx ctermfg=223 ctermbg=235 guifg=#ebdbb2
NormalFloat    xxx links to Pmenu
FloatBorder    xxx links to WinSeparator
```

> What's the output for these commands?
> 
> ```
> :hi Normal
> :hi NormalFloat
> :hi FloatBorder
> ```
> 
> With the default config, it looks like this for me:
> 
> ![image](https://user-images.githubusercontent.com/8050659/208644488-4d941c56-19c1-483f-8cc9-672c732928d7.png)

**Comment by MunifTanjim** [comment]
Just in case, can you try a different terminal emulator?

**Comment by el-og** [comment]
> Just in case, can you try a different terminal emulator?

Same thing is happening both on default MacOS X Terminal and on iTerm2

**Comment by el-og** [comment]
Ok, so I have cleaned and installed both `jackMort/ChatGPT.nvim` and `MunifTanjim/nui.nvim` for 4th time and that seems to fix an issue, although at the bottom there is a part which is still transparent for some reason 🤷 but overall now it's useable. Thanks for all the help @jackMort @MunifTanjim 
![image](https://user-images.githubusercontent.com/19407604/208665277-abff3214-0dfa-4afd-bf9f-4d40605d434f.png)
