### ISSUE TITLE
curl: (3) URL rejected: Bad hostname   

### ISSUE THREAD

**Issue by teto** [jackMort/ChatGPT.nvim#314]
When updating to master 9f8062c7c40ec082c49f10e20818333a972b8063 I get
`curl: (3) URL rejected: Bad hostname`
with the following
```
 { 'jackMort/ChatGPT.nvim',
   -- due to https://github.com/jackMort/ChatGPT.nvim/issues/265
    -- commit = "24bcca7",   IF I PIN THIS ChatGPT.nvim works fine
    config = function()
     -- passing OPENAI_API_KEY in environment for this to work
     -- huge setup at https://github.com/jackMort/ChatGPT.nvim
      require("chatgpt").setup({
        api_key_cmd = "pass show chat.openai.com",
        api_host_cmd = "echo -n 'api.openai.com'"
       })
    end,
 },
```
One of my issues is that I dont see the host used, is there some logging I could enable ? might be worth adding some checkhealth command to help debug https://neovim.io/doc/user/pi_health.html#health-commands

**Comment by teto** [comment]
thanks that fixed it.

**Comment by insv23** [comment]
Got same error message.
After some trying, I realized that `api_host_cmd` is not working as expected.
For example, `api_host_cmd = "echo -n 'api.notopenai.com'"`, it always returns `curl: (3) URL rejected: Bad hostname`.
But if I run `export OPENAI_API_HOST=api.notopenai.ai` in terminal and not use `api_host_cmd`, it works fine.
It's weird, did I miss some of the relevant descriptions in the README?
