### ISSUE TITLE
only receiving parts of the answer in :ChatGPT mode

### ISSUE THREAD

**Issue by danielreis1** [jackMort/ChatGPT.nvim#315]
![image](https://github.com/jackMort/ChatGPT.nvim/assets/10009104/a31cce07-3ea4-4e8e-9da8-7a2bcfb65cd1)

in the image you can see how I am receiving only today, instead of how are you today? in the answer.
This is after creating a new session, the problem started in a previous session.
After restarting neovim and terminal the problem persists.

**Comment by sobanieca-redocly** [comment]
Same here. Initially I thought I've messed something with settings, but apparently it's not the case. I don't think my plugin was updated in any way recently, so maybe it's an issue on OpenAI API end?

**Comment by danielreis1** [comment]
is working fine by now, didn't really anything meaningful must have indeed been a server-side thing, which is strange my other openai tools were working fine

**Comment by sobanieca-redocly** [comment]
Yes, it works fine now. Thanks!
