### ISSUE TITLE
Error starting the plugin

### ISSUE THREAD

**Issue by albertlunde123** [jackMort/ChatGPT.nvim#32]
I get the following error when running :ChatGPT,

`Error executing Lua callback: ...m/site/pack/packer/start/nui.
nvim/lua/nui/popup/init.lua:33: attempt to index local 'option
s' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/ini
t.lua:33: in function 'merge_default_options'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/ini
t.lua:79: in function 'init'
        .../site/pack/packer/start/nui.nvim/lua/nui/object/ini
t.lua:132: in function 'Popup'
        ...te/pack/packer/start/ChatGPT.nvim/lua/chatgpt/modul
e.lua:28: in function 'open_chat'
        ...te/pack/packer/start/ChatGPT.nvim/lua/chatgpt/modul
e.lua:159: in function 'openChat'
        ...nvim/site/pack/packer/start/ChatGPT.nvim/lua/chatgp
t.lua:16: in function 'openChat'
        ...m/site/pack/packer/start/ChatGPT.nvim/plugin/chatgp
t.lua:2: in function <...m/site/pack/packer/start/ChatGPT.nvim
/plugin/chatgpt.lua:1>`

**Comment by smithshelke** [comment]
yep facing the same error on my machine

**Comment by smithshelke** [comment]
https://github.com/jackMort/ChatGPT.nvim/issues/20
Duplication of this ^

**Comment by jackMort** [comment]
Is #20 solving the problem for you? Or it still occurs?

**Comment by albertlunde123** [comment]
It probably will, but im too dumb to use the feedback.
In which file should I require the setup?

**Comment by jackMort** [comment]
If you are using packer just use this snippet ```
-- Packer
use({
  "jackMort/ChatGPT.nvim",
    config = function()
      require("chatgpt").setup({
        -- optional configuration
      })
    end,
    requires = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    }
})
```

**Comment by albertlunde123** [comment]
It worked!
