### ISSUE TITLE
how could one use an `api_key_cmd` that requires sudo.

### ISSUE THREAD

**Issue by molleweide** [jackMort/ChatGPT.nvim#322]
Hi everybody,

Does anyone know if there is a way to use an `api_key_cmd` that requires sudo to retrieve the api key?
Or in other words, is there a way to make neovim promp for the password when it is running the `job` for retrieving the api key?

**Comment by jumski** [comment]
@molleweide have you solved this? i'm trying to use bitwarden-cli but it is not prompted for vault password :-(

**Comment by molleweide** [comment]
> @molleweide have you solved this? i'm trying to use bitwarden-cli but it is not prompted for vault password :-(

No, but now it seems 1password triggers their auth automatically so the issue resolved even though the original issue still bugs me a bit that i cant solve it
