### ISSUE TITLE
Ctrl-y overwrites what it yanked

### ISSUE THREAD

**Issue by DGmip** [jackMort/ChatGPT.nvim#33]
Pressing ctrl+y in ChatGPTEditWithInstructions overwrites what it yanked and immediately closes the window.
Is this the intended function?
It's great if you are trying to get a refactor or something, but I feel like it would be a lot more useful to just leave it in your yank buffer to do what you want with; I intended to get a unit test written for a simple function and it is in this way impossible to do, considering I can't copy and paste into the normal ChatGPT command, either :(

**Comment by martasd** [comment]
I find it also unexpected but in my case useful. Looks like it's a misnomer.

**Comment by DGmip** [comment]
Yeah it should really be 'replace' or 'accept edit'
