### ISSUE TITLE
flows.inline edit file does not exist

### ISSUE THREAD

**Issue by ashish10alex** [jackMort/ChatGPT.nvim#35]
Hi in the [latest commit](https://github.com/jackMort/ChatGPT.nvim/commit/fb47b4c64ba021f890ce2b36d031c429ca80196d) there seems to be a line added  in `lua/chatgpt/module.lua` 

```
local InlineEdit = require("chatgpt.flows.inline_edit")
```

However no such file structure exists, which is causing the installation and functionality to break.

**Comment by jackMort** [comment]
Please update to newest version, I'm working on some new features and forgot to remove that line when committing other changes

**Comment by Icy-Thought** [comment]
Just updated plugin to latest version and it appears as if the issue is still there. :confused:

**Comment by jackMort** [comment]
It should works now, sorry for that

**Comment by Icy-Thought** [comment]
No worries! It works as expected as of now. Appreciate the effort! :smile:
