### ISSUE TITLE
Please update the default config to prevent usage of deprecated AI models

### ISSUE THREAD

**Issue by realestninja** [jackMort/ChatGPT.nvim#350]
Hi there,

just got the mail from openAI saying that models like davinci will be shut-down in Jan 2024: https://platform.openai.com/docs/deprecations

I checked the documentation of ChatGPT.nvim and saw that it is possible to set up a config but I was just wondering if there will be an update for this, since everyone, using this plugin with defaults, will be affected.

Looking forward to hearing from you 👋🏾

**Comment by jackMort** [comment]
Hi, we don't use the davinci model

**Comment by realestninja** [comment]
My bad, I was on an older version where it was set to use davinci.
