### ISSUE TITLE
<Tab> No longer moves cursor across panes in edit with instructions view

### ISSUE THREAD

**Issue by Aaronik** [jackMort/ChatGPT.nvim#352]
It appears that 1f69ba297388bccc604a76d9c940cb26156c5cd1 broke <Tab> moving the cursor from window to window.

**Comment by v3ceban** [comment]
+1. Issue only appears in "edit with instructions" mode. Opening help or settings menu temporarily fixes it

**Comment by Aaronik** [comment]
Here's a PR that fixes it: https://github.com/jackMort/ChatGPT.nvim/pull/388

**Comment by kohane27** [comment]
Thank you so much for this fix! It's bugged me for a long time.

**Comment by Aaronik** [comment]
My pleasure! I'm happy to hear it's helping others as well :)

**Comment by Aaronik** [comment]
Gah, I'm seeing that for some reason this fix only fixed it _for the first time you open the window_. Whaaaaaaaaat? I'll keep lookin' into it

**Comment by Aaronik** [comment]
Ok, here's another fix that fixes the subsequent opens: https://github.com/jackMort/ChatGPT.nvim/pull/390
