### ISSUE TITLE
custom question_sign does't work

### ISSUE THREAD

**Issue by Jezda1337** [jackMort/ChatGPT.nvim#4]
use({
	"jackMort/ChatGPT.nvim",
	config = function()
		require("chatgpt").setup({
			question_sign = "🙂",
		})
	end,
	requires = {
		"MunifTanjim/nui.nvim",
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope.nvim",
	},
})
here is the config that I using for this plugin, and the sign does't work, I also try to put anything there didn't override the default one, it's not big deal tbh 🧑‍💻

**Comment by Jezda1337** [comment]
Its working now, I didn't do :PackerSync bcs that didn't work...

**Comment by jackMort** [comment]
great, thanks for letting me know :)
