### ISSUE TITLE
Groq is too fast

### ISSUE THREAD

**Issue by Aman9das** [jackMort/ChatGPT.nvim#413]
The output from https://console.groq.com gets cut off due to the speed of inference.

![image](https://github.com/jackMort/ChatGPT.nvim/assets/39594914/9ab76b6b-e063-4cd3-add8-ecf713ff2583)

**Comment by Aman9das** [comment]
using environment variables OPENAI_API_HOST and OPENAI_API_KEY

**Comment by ehsan2003** [comment]
how you have set model ?

**Comment by thiswillbeyourgithub** [comment]
Personnaly I ended up making a quick and dirty docker compose to run litellm and highjack request. That allowed me to use Claude sonnet 3.5 as well as online searching models.

**Comment by jackMort** [comment]
increase max_tokens
