### ISSUE TITLE
Exiting any window causes 'ChatGPT' to throw errors

### ISSUE THREAD

**Issue by felipejoribeiro** [jackMort/ChatGPT.nvim#422]
Great Plugin!

## Context:

branch main
commit df53728

```lua
-- config
return {
  'jackMort/ChatGPT.nvim',
  event = 'VeryLazy',
  config = function()
    require('chatgpt').setup()
  end,
  dependencies = {
    'MunifTanjim/nui.nvim',
    'nvim-lua/plenary.nvim',
    'folke/trouble.nvim',
    'nvim-telescope/telescope.nvim',
  },
}

```

I'm having an issue when exiting the prompt window:

![image](https://github.com/jackMort/ChatGPT.nvim/assets/39244876/4d82b4af-a3d5-4186-9b69-bf86eb1577d7)

```
Error detected while processing WinClosed Autocommands for "1006":
Error executing lua callback: ...i/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:189: WinCl
osed Autocommands for "1006"..BufWinLeave Autocommands for "<buffer=8>": Vim(mkview):E32: No file na
me
stack traceback:
        [C]: in function 'nvim_win_close'
        ...i/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:189: in function '_close_window'

        ...i/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:268: in function 'hide'
        ....local/share/nvim/lazy/nui.nvim/lua/nui/layout/float.lua:175: in function 'hide_box'
        .../.local/share/nvim/lazy/nui.nvim/lua/nui/layout/init.lua:364: in function 'hide'
        .../.local/share/nvim/lazy/nui.nvim/lua/nui/layout/init.lua:119: in function <.../.local/sha
re/nvim/lazy/nui.nvim/lua/nui/layout/init.lua:118>
```
It happens when i'm inside the prompt window of "ChatGPT", and i close it with `:q`, it leaves a black opaque square behind as well as follows:

![image](https://github.com/jackMort/ChatGPT.nvim/assets/39244876/1b33f82e-0cb3-4461-a6f3-5c00cef61507)

When i exit with `<C-c>` the behavior is almost the same, but the 'prompt' window stays behind and i have to quit it with `:q` because the former way doesn't work anymore.

Thanks for the amazing plugin.

**Comment by ben-wall** [comment]
Every single time this plug-in throws an error it breaks my entire VIM session because I can't escape it showing errors every single time I press a key, so it's _dangerous_ to use when I have multiple buffers with work open And since it's inception, I've avoided doing so because of just this.

**Comment by felipejoribeiro** [comment]
Exactly. A more graceful error handling would be appreciated.

But I have been able to use this  plugin very reliably for the past two months...
Some new releases may have solved my problem.

So i will close this issue. @ben-wall, fell free to create a new one with your specific setup and context.
