### ISSUE TITLE
occasional bug

### ISSUE THREAD

**Issue by danielreis1** [jackMort/ChatGPT.nvim#437]
![image](https://github.com/jackMort/ChatGPT.nvim/assets/10009104/d73d3a0f-e05d-406d-9e13-4dd943a2a9b0)
occasional bug, no real good reason it just happens from time to time, not sure how to reproduce

hangs on:
![image](https://github.com/jackMort/ChatGPT.nvim/assets/10009104/420d5c9b-ea24-4c4d-a3ed-b9e0569b9133)
just stays loading forever

it always happened since I started using this tool
It just hangs there until I restart neovim

anyone knows how to fix this without having to restart neovim, that's kind of the worst part, reloading the module doesnt appear to fix anything

**Comment by jackMort** [comment]
it should be solved
