### ISSUE TITLE
`?` keymap help

### ISSUE THREAD

**Issue by jackMort** [jackMort/ChatGPT.nvim#44]
### Discussed in https://github.com/jackMort/ChatGPT.nvim/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **RhydianJenkins** December 29, 2022</sup>
Hi.

Thanks so much for this plugin. I use it daily :)

I've noticed that we've recently been blessed with several new features (such as sessions and api request params), and have since also been given several new keybinds to remember.

Could we get something like nerdtree (example below) where the user could press `?` to see a quick summary/cheat sheet of all the possible buttons? It's getting hard to track!

![image](https://user-images.githubusercontent.com/9198690/209973542-87b83a2c-9aeb-44c5-9bdf-13ef68e964b9.png)

![image](https://user-images.githubusercontent.com/9198690/209973566-871e2eee-8782-4dae-be72-f9d9c38cf9a2.png)

Thanks</div>

**Comment by Urthor** [comment]
Excellent suggestion from Rhydia!

**Comment by tricktux** [comment]
Friendly bump!

**Comment by drskoolie** [comment]
I've been looking for this as well. Another bump from me.

**Comment by Moerliy** [comment]
I played a bit with the Nui layout and the way settings can be toggled on and off. Making something similar to toggle help does work. I have something rudimentary working now but it is buggy and I'm struggling with Lua in general. Haven't coded with it that much. I will push to a fork when I have some more time. Maybe in some days.
