### ISSUE TITLE
Size for popup_layout no longer respected

### ISSUE THREAD

**Issue by michaelnew** [jackMort/ChatGPT.nvim#456]
This is what my config looks like, and it worked fine until a recent update. Now the pop up shows at what I assume is about 80% in both dimensions no matter what the values in the config are set to.
```lua
require("chatgpt").setup({
    popup_layout = {
      default = "center",
      center = {
        width = "100%",
        height = "100%",
      },
    }
-- ...
})
```

**Comment by antosha417** [comment]
Hey @michaelnew I tried to reproduce it, and do not see any problem. I tired to do 100%, 95%, 60%. Everything seems to be worknig

**Comment by jackMort** [comment]
cannot reproduce

**Comment by michaelnew** [comment]
Hey, sorry I didn't see the activity on this. I haven't used it in a while, but I just checked on the latest commit and I'm not seeing this happen anymore. So I'm not sure what was going on, but it looks resolved one way or another.
