### ISSUE TITLE
You exceeded your currunt qouta

### ISSUE THREAD

**Issue by kirubel-web** [jackMort/ChatGPT.nvim#458]
You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
```
require("chatgpt").setup({
  api_key = "my api key here",
    openai_params = {
      model = "gpt-3.5-turbo",
    },
})

vim.api.nvim_set_keymap('n', '<leader>cg', ':ChatGPT<CR>', { noremap = true, silent = true })

```

does the plugin require payed version of open ai?

**Comment by riordant** [comment]
yes you need an OpenAI API key  - you do not interact with ChatGPT here through the same means you would on the OpenAI UI. check the README.

**Comment by kirubel-web** [comment]
thanks

> yes you need an OpenAI API key - you do not interact with ChatGPT here through the same means you would on the OpenAI UI. check the README.

thanks i appreciate the response, I guess i need to buy an OpenAI API credit.
