### ISSUE TITLE
Impruve INSTALL GUIDE to users don't use LUA & PACKER (init.vim)

### ISSUE THREAD

**Issue by jslipak** [jackMort/ChatGPT.nvim#46]
First of all, Thank You for this Plug.
I want to use but I don't use vim with init.lua and Packer.

I try to add all the dependencies with my gestor of the package:
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.0' }
Plug 'muniftanjim/nui.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'jackmort/chatgpt.nvim'

and when I use it in normal mode and type :chatgpt, I get the next error.

Error executing Lua callback: ...local/share/nvim/plugged/nui.nvim/lua/nui/popup/init.lua:33: attempt to index local 'options' (a nil value)
stack traceback:
        ...local/share/nvim/plugged/nui.nvim/lua/nui/popup/init.lua:33: in function 'merge_default_options'
        ...local/share/nvim/plugged/nui.nvim/lua/nui/popup/init.lua:79: in function 'init'
        ...ocal/share/nvim/plugged/nui.nvim/lua/nui/object/init.lua:132: in function 'Popup'
        ...l/share/nvim/plugged/chatgpt.nvim/lua/chatgpt/module.lua:53: in function 'open_chat'
        ...l/share/nvim/plugged/chatgpt.nvim/lua/chatgpt/module.lua:201: in function 'openChat'
        ...a/.local/share/nvim/plugged/chatgpt.nvim/lua/chatgpt.lua:24: in function 'openChat'
        ...local/share/nvim/plugged/chatgpt.nvim/plugin/chatgpt.lua:2: in function 
         <...local/share/nvim/plugged/chatgpt.nvim/plugin/chatgpt.lua:1>

Thank you for your efforts again, I'll wait for your help because I want to use your plugin.
I know at some moment, I have to pass to lua and packer!

**Comment by user19685757** [comment]
It's ok. I use packer and I have same errors.

**Comment by MunifTanjim** [comment]
https://github.com/jackMort/ChatGPT.nvim/issues/20

**Comment by Khang5687** [comment]
Add this to the end of your init.vim

`lua require('chatgpt').setup()`

**Comment by jslipak** [comment]
Thank you!,  I fix my configuration a few days ago.

//.env
OPENAI_API_KEY=uoeuaoehsuntaoeuhoaetuhsaounth
//.bashrc  || .zshrc
# add variables and protect to expose in git 
if [ -f .env ]; then
  export $(cat .env | xargs)
fi
// init.vim
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.0' }
Plug 'muniftanjim/nui.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'jackmort/chatgpt.nvim'
lua require('chatgpt').setup()
