### ISSUE TITLE
Ability to override highlight groups

### ISSUE THREAD

**Issue by olimorris** [jackMort/ChatGPT.nvim#47]
A [colorscheme](https://github.com/olimorris/onedarkpro.nvim) author here.

Searching through the code base, I can see that there are some highlight groups that are applied during setup, namely `ChatGPTQuestion` and `ChatGPTTotalTokens`.

I'd like to support the plugin out of the box in my colorscheme but with the current implementation, ChatGPT overwrites any highlight groups I set.

Is it possible to check if `ChatGPTQuestion` and `ChatGPTTotalTokens` highlight groups already exist before setting them? I think `vim.api.nvim_get_hl_by_name()` would do the trick.

**Comment by MunifTanjim** [comment]
> Is it possible to check if ChatGPTQuestion and ChatGPTTotalTokens highlight groups already exist before setting them? I think vim.api.nvim_get_hl_by_name() would do the trick.

The vim way is to set hl as default, i.e. pass `default = true` to `nvim_set_hl`. (`:help highlight-default`)
