### ISSUE TITLE
non-existing buffer when closing window before receiving an answer.

### ISSUE THREAD

**Issue by niderhoff** [jackMort/ChatGPT.nvim#5]
When you close the buffer before receiving an answer, you get all sorts of errors related to non-existing buffer.

<img width="853" alt="grafik" src="https://user-images.githubusercontent.com/5991543/207864079-5d2fe8e2-14e5-4387-a6f8-0f15dc61e38f.png">

How to reproduce:

* `:ChatGPT`
* write hello
* quickly press CTRL+C

**Comment by jackMort** [comment]
It should be solved now.
