### ISSUE TITLE
 difficulty with closing `ChatGPTEditWithInstructions` window.

### ISSUE THREAD

**Issue by RichestHumanAlive** [jackMort/ChatGPT.nvim#54]
Seems like there is some difficulty with closing `ChatGPTEditWithInstructions` window.

instead of closing floating windows, hitting mapped keys triggers the normal mode on the prompt.

For now use `:q` to exit this windows (just for this window. For the other windows there is no issue)

Here are my mappings :

```lua
keymaps = {
    close = { "jk", "kj", "<Esc>" },
    yank_last = "<C-y>",
    scroll_up = "<C-u>",
    scroll_down = "<C-d>",
    toggle_settings = "<C-o>",
    new_session = "<C-n>",
    cycle_windows = "<Tab>",
  },
```

**Comment by el-og** [comment]
I have same issues, but for all of the ChatGPT windows

**Comment by TheJoeSchr** [comment]
It seems you must be in insert mode first, then you can `<C-c>`. `Esc` doesn't work for me

**Comment by TheJoeSchr** [comment]
Also my custom keybind to close buffer works for this:
```
nnoremap <silent> Q     :bd <CR>
```

**Comment by dk-salesforce** [comment]
I got the same issue

**Comment by Aaronik** [comment]
I can't even press `<C-c>` to close it from insert (or normal) mode, I have to use `:bd`.

**Comment by comiluv** [comment]
I would also like to press ```<C-c>``` to close ```ChatGPTEditWithInstructions``` window instead of ```:q``` or ```:bd```

**Comment by 00sapo** [comment]
PR https://github.com/jackMort/ChatGPT.nvim/pull/141 partially solve this issue mapping both insert and normal mode. I would like to give the user the ability to add its own key maps though. As soon as @jackMort accept this PR, I'll work on that
