### ISSUE TITLE
Add command to open a fresh new chat

### ISSUE THREAD

**Issue by phcerdan** [jackMort/ChatGPT.nvim#56]
I discovered I miss this option when I started the chat with an "Hola", and chatGPT was answering me always in Spanish, even when all the next questions were in English.

**Comment by Akeboshiwind** [comment]
There's keybindings at the bottom of the README.
`<C-n>` starts a new session :)

**Comment by phcerdan** [comment]
Ouch, I missed it, thanks @Akeboshiwind
