### ISSUE TITLE
Modularizing query functionality to create 'coding helpers'

### ISSUE THREAD

**Issue by dewoller** [jackMort/ChatGPT.nvim#60]
Hi Jack

I love your work!  The code that encapsulates the completion query types are very good, quite clean and readable.  The package is very playful and functional, really showing what can be done with the openAI api.

My use case is less interactive. I would like to use ChatGPT to help with day to day coding tasks, asking the API to  'document this diff', or 'create a test for this function'.  I propose extend your ChatGPT.nvim package  to create vim text actions for specific ChatGPT prompts.  

To do this, I need to modularise your query functionality. You have started this task with the completions, especially the `custom_code_action`, but I would like to be able to specify all the OpenAI parameters.  E.g. substitute/append the text, the actual prompt, 

Also, I would like to specify the prompts and query parameters, defining a specific text action in an external file, sourced at runtime, like is done with snippets.  This way, everyone can create their personal coding-helpers, without having to edit the plugin.  

What do you think?  I would be very happy if you wanted to lead this work, but I am also happy to take it on.  Your code is very sensible.

Also, what is the license for the project?

Thanks, Dennis

**Comment by jackMort** [comment]
Hi, thank you. I was thinking about something like this, my idea was to expose some interface to define code actions via JSON config, so everyone will have option to add own "snippets", i started working on that, i want to publish it this week.

**Comment by jackMort** [comment]
I need to think what licence to use but basically i don't want to limit reusage of my code any way

**Comment by dewoller** [comment]
Oh Lech,  that sounds great, it is exactly what I want.  I am happy to help you, feel free to assign tasks to me.

**Comment by jackMort** [comment]
thanks @dewoller for your contribution! I just rewrited my code to define actions as json snippets, and allow define new ones by users, I just need to add some documentation about that - i will do that in some spare time.
