### ISSUE TITLE
Error happened after asking for a while

### ISSUE THREAD

**Issue by liketoeatcheese** [jackMort/ChatGPT.nvim#64]
Hey mate, in loveeeee with the plugin. So helpful! I think I'm hitting some limit, getting this error. Any thoughts? 
// API ERROR: 14 is greater than the maximum of 1 - 'top_p'

**Comment by jackMort** [comment]
maybe you changed `top_p` parameter ? plase make screenshot with opened settings panel <C-o>

**Comment by liketoeatcheese** [comment]
Here's my packer:
-- ChatGPT
  -- Packer
  use({
    "jackMort/ChatGPT.nvim",
    config = function()
      require("chatgpt").setup({
       -- optional configuration
      })
    end,
    requires = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    }
  })

**Comment by liketoeatcheese** [comment]
![image](https://user-images.githubusercontent.com/88610355/213574711-6a4dd35d-d15f-422e-90c3-419dfaa14013.png)

**Comment by jackMort** [comment]
![screenshot-raw githubusercontent com-2023 01 20-09_54_07](https://user-images.githubusercontent.com/163699/213655099-4b0d493c-9f75-4ea0-8d90-0b9d2cbaf739.png)

Open settings panel using keybinding <C-o> and check if top_p param is equal or less 1 if not you can edit it there
