### ISSUE TITLE
Token price & chatGpt model

### ISSUE THREAD

**Issue by mattiasbonte** [jackMort/ChatGPT.nvim#66]
Hello, i I have 2 questions,

I was wondering if it is possible to hide/toggle the tokens/price? I can't seem to find the configuration option to do this.

It's causing some issues when typing a long query, then the text goes behind it.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/65280774/214441247-ab762def-b817-437e-9c54-1e26542ed6e4.png">
The same happens for a long chat gpt answers, then the answer is printed below the token label and unreadable.
<img width="750" alt="image" src="https://user-images.githubusercontent.com/65280774/214441146-5b316507-968b-4567-9a54-31f0453354ba.png">

And the other question is more informational. The plugin is called ChatGPT, but I get very different answers while using this plugin compared to using the [web based version](https://chat.openai.com).  Any idea of why that could be?

Thanks for your time!

**Comment by fjchen7** [comment]
Sorry, maybe unrelated to your issue. What are the TOKENS and PRICES here? Does it charge me? But I didn't bind my credit card to chatGPT.

**Comment by KyouKiSu** [comment]
Same issue

**Comment by DGmip** [comment]
> Sorry, maybe unrelated to your issue. What are the TOKENS and PRICES here? Does it charge me? But I didn't bind my credit card to chatGPT.

The pricing model grants you a certain amount of tokens to use in the first 3m of use, then a card is required to pay monthly for your use; so the functionality is actually the same regardless of whether you have set up the card or not.

**Comment by DGmip** [comment]
If this issue is a stuck could we please have an option to hide the tokens: / price text so that we don't have to type under it?
