### ISSUE TITLE
Terrible performance while inside neovide..

### ISSUE THREAD

**Issue by StrictlyMonad** [jackMort/ChatGPT.nvim#70]
I recently installed this plugin and noticed that it suffered from performance issues while used inside Neovide. Any ideas to why that is?

Steps to replicate:
1. Launch neovide.
2. Launch `ChatGPT`.
3. Write random text and hit enter for generated answer.
4. Hide -> show Neovide.

You will most likely experience some form of input lag in step 3 and a massively degraded performance in step 4.

Installation steps:
```lua
       {
        "jackMort/ChatGPT.nvim",
        event = "UIEnter",
        opts = {
            chat_window = {
                border = { text = { top = "ChatGPT-3" } },
            },
        },
```

**Comment by jackMort** [comment]
I'm using neovide from time to time, tried few times to reproduce the issue but I cannot.

**Comment by StrictlyMonad** [comment]
Just did some testing and it appears to be something faulty with `--maximized` argument when combined with `--multigrid`. Perhaps I should report it in neovide's very own repository? :thinking:
