### ISSUE TITLE
Are the responses generated for these requests?

### ISSUE THREAD

**Issue by lerner-zhang** [jackMort/ChatGPT.nvim#71]
![Screen Shot 2023-02-08 at 16 42 02](https://user-images.githubusercontent.com/116086828/217479645-8faf2dba-c198-4541-aae2-123d5b4acfa4.jpg)
The error reads that: 
>  // API ERROR: Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error
   │ and would like to appeal, please contact support@openai.com.

But I wonder if the price indicates that the response had been generated but was just not displayed? 

This information would be essential to this issue: I am in China and the VPN I use cannot hide/change my IP location.

**Comment by jackMort** [comment]
If error occours there's no other responses, I don't know how it works on they end but looks like tokens were taken anyway
