### ISSUE TITLE
Functional Question: Pasting text from clipboard into prompt window

### ISSUE THREAD

**Issue by fabian-gubler** [jackMort/ChatGPT.nvim#79]
**Behavior:** 
When pressing Ctrl+shift+v the text is not inserted into the prompt window

**Use case:**

- I oftentimes write very long prompts. 
- It is not possible to view longer prompts within the prompt window. Also it is difficult to edit them.

Consequently, it would be nice to be able to write longer prompts in a normal neovim buffer and then paste it to the prompt window

**Additional Considerations:**
If telescope / nui.nvim does not allow this, it would be nice to have a command similar to "ChatGPTEditWithInstructions".
This command would allow the user to directly send a visual selection into text-davinci.

**Comment by fabian-gubler** [comment]
**New Observation:**
My described issue is present when yanking text from a neovim buffer.
I have just found out that when I copy text from another source (e.g. browser), I can press ctrl+shift+v and it inserts the text.

**Comment by mmngreco** [comment]
> it would be nice to have a command similar to "ChatGPTEditWithInstructions".

Exactly, I've found this try to do exactly this, but doesn't work over markdown files 🤷
