### ISSUE TITLE
Nice but misleading plugin name?

### ISSUE THREAD

**Issue by j-xella** [jackMort/ChatGPT.nvim#82]
The project page contains the correct description of what it does. I understand it now, after I spent some time learnig about AI and models and so on. However, as a newbie in AI field, this neovim plugin confused me into expecting different things from it.

There are many reasons why this plugin can be called **ChatGPT**. They are described on the project home page, and they are all correct. However, for most people the word **ChatGPT** means something [else](https://openai.com/blog/chatgpt/) now.

When I found this project (top result if you google "neovim chatgpt"), I thought it would be a neovim interface to [this](https://chat.openai.com/chat). I did not understand the description fully; however, many familiar keywords like **OpenAI**, **chat**, **GPT**, **3** were present. Walks like a duck and quacks like a duck, right? So I installed it, and obviously got something else. Some differences:

 * It is monetized differently
 * It producces different answers to the same questions (different models GPT-3 vs. GPT-3.5)
 * My saved [web chats](https://chat.openai.com/chat) are nowhere to be seen.

I could say it is just me, but judging by the questions many peolple ask, I believe there are many more people who get misled in the same way and then waste their time and yours.

A more precise name for this plugin would probably be **OpenAI_API.nvim**, or something similar. But if changing the name is not an option, there could at least be a disclaimer in big bold letters, that this plugin provides access to OpenAI API, and **[ChatGPT on the web](https://chat.openai.com/chat) and [OpenAI API](https://openai.com/api/) are _not the same things_**!!!

**Comment by thenbe** [comment]
_The_ `chatGPT` api has just been released 🚀

 https://platform.openai.com/docs/guides/chat

**Comment by jackMort** [comment]
misleading plugin name?, not anymore ;) just switched to gpt-3.5-turbo model by default

**Comment by j-xella** [comment]
OK, maybe the model is the same now, but pricing is still separate, and the chats saved on the web are not accessed via the vim plugin, correct?
