### ISSUE TITLE
[Feature request]: Promp bigger and editable

### ISSUE THREAD

**Issue by aemonge** [jackMort/ChatGPT.nvim#84]
So when asking long questions, I want a bigger prompt. Also when having spelling error while typing I want to `<esc>` and edit my promt as if it where a regular window. I would prefere having my normal mappings for moving acroos the chat windows, and just a simple extra mapping to send the promt to the chat, and even better which such extra mapping you could visually select anywhere and send it to the chat.

Then for coping and scrolling, I would also stick to our own mappings. So I rather move into the response window and yank normally, than <c-y> the last response.

Anyways, take this as a wish, I stil think this pluging is amezing <3

**Comment by tricktux** [comment]
I highly agree with this point. I also want to highlight that this is a god sent plugin. Amazing work. A prompt that's editable is the only missing peace. Right now, I edit long prompts in markdown, yank and then paste. Not ideal.

**Comment by DGmip** [comment]
I'm pressing ctrl+enter and it's not

**Comment by aemonge** [comment]
Same here

**Comment by jackMort** [comment]
seems like ctr+enter is not supported by all of the terminals please try remap to something else e.g. C+a 
```
      require("chatgpt").setup({
        keymaps = {
          submit = '<C-a>'
        }
      })
```
take look at #99 for context

**Comment by aemonge** [comment]
Working :) Thanks
