### ISSUE TITLE
Error when installing with vim-plug

### ISSUE THREAD

**Issue by KroccoHi** [jackMort/ChatGPT.nvim#88]
![image](https://user-images.githubusercontent.com/41275128/222879257-bc56a02d-c42a-414c-b385-3e43f0197d76.png)
I don't know anything about Lua, so I don't know how to set the options from within vim. If someone could point me in the right direction that would be great. Thanks a lot.

**Comment by n3ry7** [comment]
Is packer necessary to install this plugin?

I also use vim-plug as my plugin manager

**Comment by n3ry7** [comment]
I got this!

add these to your init.vim
call plug#begin()
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'MunifTanjim/nui.nvim'
Plug 'jackMort/ChatGPT.nvim'
call plug#end()

lua <<EOF
-- chat gpt
require("chatgpt").setup()
EOF

Set environment variable called $OPENAI_API_KEY 

worked for me

**Comment by n3ry7** [comment]
Sure. 

I will create the PR

**Comment by MunifTanjim** [comment]
https://github.com/jackMort/ChatGPT.nvim/issues/20
