### ISSUE TITLE
// API ERROR: Invalid URL (POST /v1/chat/completions)

### ISSUE THREAD

**Issue by n3ry7** [jackMort/ChatGPT.nvim#89]
I was able to run the prompt only once.

Now I get this error message whenever I try to prompt

**Comment by n3ry7** [comment]
It was an error in my setup config

**Comment by aemonge** [comment]
What was your error?

I'm facing the same issue here

**Comment by n3ry7** [comment]
I had this in my init.vim

require("chatgpt").setup({
  welcome_message = WELCOME_MESSAGE, -- set to "" if you don't like the fancy godot robot
  loading_text = "loading",
  question_sign = "", -- you can use emoji if you want e.g. 🙂
  answer_sign = "ﮧ", -- 🤖
  max_line_length = 120,
  yank_register = "+",
  chat_layout = {
    relative = "editor",
    position = "50%",
    size = {
      height = "80%",
      width = "80%",
    },
  },
  settings_window = {
    border = {
      style = "rounded",
      text = {
        top = " Settings ",
      },
    },
  },
  chat_window = {
    filetype = "chatgpt",
    border = {
      highlight = "FloatBorder",
      style = "rounded",
      text = {
        top = " ChatGPT ",
      },
    },
  },
  chat_input = {
    prompt = "  ",
    border = {
      highlight = "FloatBorder",
      style = "rounded",
      text = {
        top_align = "center",
        top = " Prompt ",
      },
    },
  },
  openai_params = {
    model = "text-davinci-003",
    frequency_penalty = 0,
    presence_penalty = 0,
    max_tokens = 300,
    temperature = 0,
    top_p = 1,
    n = 1,
  },
  openai_edit_params = {
    model = "code-davinci-edit-001",
    temperature = 0,
    top_p = 1,
    n = 1,
  },
  keymaps = {
    close = { "<C-c>", "<Esc>" },
    yank_last = "<C-y>",
    scroll_up = "<C-u>",
    scroll_down = "<C-d>",
    toggle_settings = "<C-o>",
    new_session = "<C-n>",
    cycle_windows = "<Tab>",
    -- in the Sessions pane
    select_session = "<Space>",
    rename_session = "r",
    delete_session = "d",
  },
})

which is the default config but was giving me an error,  I  don't understand lua really well. But If i leave it empty it works fine.

      require("chatgpt").setup()

**Comment by aemonge** [comment]
That's wierd, I've just set it as you mentioned but it's stil failing on my side:

**config**:
```lua
local M = {}

table.insert(M, {
  "jackMort/ChatGPT.nvim",
  dependencies = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim"
  },
  config = function()
    require("chatgpt").setup()
    require "which-key".register({
      c = {
        name = "ChatGPT",
        c = { [[:ChatGPT<cr>]], "Simple" },
        a = { [[:ChatGPTActAs<cr>]], "Act as .." }
      }
    }, {
      mode = "n",
      prefix = "<leader>",
      buffer = nil,
      silent = true,
      noremap = true,
      nowait = true,
    })
  end
})

return M
```

**Error**:
![image](https://user-images.githubusercontent.com/1322348/223137208-d59738ff-c828-4ce3-9911-c30a82c31bc8.png)

I can't find any logs.

**Comment by aemonge** [comment]
The error disappears after a full OS reinstall. ( I did the reinstallation for other reasons )

**Comment by Aaronik** [comment]
I'm getting the same error, and I've been getting it for weeks. I've kept hoping that updating the plugin will help, but ultimately it hasn't, and I'm ready for this to be working again. @jackMort, any ideas what might be causing this? 

![image](https://user-images.githubusercontent.com/1324601/226504784-a5388509-423b-49b0-80d6-f42037dea9de.png)

This is happening to me whether I give an empty config or not. For reference, I'm using lazy, and my main config is like this:

```
  {
    'jackMort/ChatGPT.nvim',
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    },
    keys = { { "<leader>a", "<cmd>ChatGPT<CR>" } },
    opts = {
      welcome_message = "Welcome!", -- set to "" if you don't like the fancy robot
      loading_text = "loading",   
      question_sign = "", -- you can use emoji if you want e.g. 🙂
      answer_sign = "ﮧ", -- 🤖
      max_line_length = 120,
      keymaps = {
        close = { "<C-c>", "<Esc>" },
        yank_last = "<C-y>",
        scroll_up = "<C-u>",
        scroll_down = "<C-d>",
        toggle_settings = "<C-o>",
        new_session = "<C-n>",
        cycle_windows = "<Tab>",
      },  
      chat_layout = {
        relative = "editor",
        position = "50%",
        size = {
          height = "80%",
          width = "80%",
        },
      },
      chat_window = {
        border = {
          highlight = "FloatBorder",
          style = "rounded",
          text = {
            top = " ChatGPT ",
          },
        },
      },
      chat_input = {
        prompt = "  ",
        border = {
          highlight = "FloatBorder",
          style = "rounded",
          text = {
            top_align = "center",
            top = " Prompt ",
          },
        },
        win_options = {
          winhighlight = "Normal:Normal",
        },
      },
      openai_params = {
        model = "text-davinci-003",
        frequency_penalty = 0,
        presence_penalty = 0,
        max_tokens = 300,
        temperature = 0,
        top_p = 1,
        n = 1,
      },
      openai_edit_params = {
        model = "code-davinci-edit-001",
        temperature = 0,
        top_p = 1,
        n = 1,
      },
    }
  },
```
This might be wrong, but I believe this started happening the first time after I pressed tab in there and went to a new page.

**Comment by xuyangy** [comment]
The culprit in your config might be:
```
openai_params = {
  model = "text-davinci-003",
 ...
```
Check out the config in the up to date README, "text-davinci-003" is replaced by "gpt-3.5-turbo".
