### ISSUE TITLE
[Feature Request] Highlight text to send it to ChatGPT with instructions

### ISSUE THREAD

**Issue by DGmip** [jackMort/ChatGPT.nvim#93]
One of my most common developer use cases for chatgpt involves pasting some code and asking for an amendment, fix or explanation to that snippet...

I've tried changing the edit_with_instructions() model to the chatGPT one, but understandably it just errors.

What I'd like is the same functionality as that, but for it to go to chatgpt and not davinci code. 

:ChatGPTWithInstructions could take the visually selected code, allow you to add text to the request body with the input as before and send the whole thing off to chatpgt. If no text is added by you, it just sends the code snippet itself.

Without this functionality I only have about 10% usability for this plugin whilst inside of vim.

**Comment by sahglie** [comment]
The work around I found for this, is to create an empty buffer.  Then dump the code plus comments I want into that buffer. In some cases, code from multiple files, not something that can just be visually selected. Once buffer is ready call :ChatGPTWithInstructions

**Comment by DGmip** [comment]
> The work around I found for this, is to create an empty buffer. Then dump the code plus comments I want into that buffer. In some cases, code from multiple files, not something that can just be visually selected. Once buffer is ready call :ChatGPTWithInstructions. Works pretty well IMO.

Thank,s but as I mentioned, this does not use ChatGPT model and can't be changed to use it as it throws an error.

**Comment by DGmip** [comment]
Looks like code-davinci-edit-001 is being deprecated in favour of 3.5 anyway so @jackMort will have to change it over pretty soon (hopefully very soon I can't wait for this to work!)
This ticket should be closed once that's done.

**Comment by 00sapo** [comment]
Isn't a custom action.json enough?
