### ISSUE TITLE
Remapping submit not working

### ISSUE THREAD

**Issue by PaulKushch** [jackMort/ChatGPT.nvim#99]
Hi,
I am trying to remap `submit` button but it does not work.

`C-Enter` just jumps down a line:

![image](https://user-images.githubusercontent.com/5386035/224341006-36df14d1-6d56-45f0-b376-8300aefeb710.png)

I tried to remap but remapping does not seem to work either:

Remap config is:

```
{ 
"jackMort/ChatGPT.nvim",
config = function()
	require("chatgpt").setup({
		-- optional configuration
		keymaps = {
			submit = "<C-e>",
		},
	})
end,
requires = {
	"MunifTanjim/nui.nvim",
	"nvim-lua/plenary.nvim",
	"nvim-telescope/telescope.nvim",
},
},
```
Is this the correct way?

It seems that the `Prompt` window is not working properly for me, I can not see a `caret` for example:
![image](https://user-images.githubusercontent.com/5386035/224340169-e21b3c4b-1085-49ad-9aea-84f82db34331.png)

**Comment by edofic** [comment]
I have the same issue, also cannot remap. I mitigated by using a version that is few days old (multiline prompt + submit was just introduced. Full config

```lua
  {
    "jackMort/ChatGPT.nvim",
    commit = '8820b99c', -- March 6th 2023, before submit
    config = function()
      require("chatgpt").setup({})
    end,
    requires = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    }
  },
```

**Comment by PaulKushch** [comment]
@edofic Great! Thanks, it works now! So something is broken in latest commit?

**Comment by jackMort** [comment]
could you please check the output of `:messages ` command when runing on latest branch, I cannot reproduce it

**Comment by edofic** [comment]
`:messages` is empty for me (tested on 3ad20aeee036378478bfb75788c6e287964ece8e).
fyi I'm using lunarvim - will try to reproduce this on a more minimal config 🤞

**Comment by edofic** [comment]
I can reproduce on a fresh (docker container) nvim v0.8.1, full config below (just ` .config/nvim/init.lua` + I bootstrapped packer)


```lua
return require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  use {
    "jackMort/ChatGPT.nvim",
    config = function()
      require("chatgpt").setup({
        keymaps = {
          submit = 'C-e'
        }
      })
    end,
    requires = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim"
    }
  }

end)
```

**Comment by RazaGR** [comment]
@edofic  you need to add it like `submit = '<C-e>'`

@jackMort there is a typo in READ.md ` submot = "<C-Enter>",` should say `submit`

and <C-Enter> or <C-<CR>> does not work for me either.

**Comment by edofic** [comment]
@RazaGR thanks 🤦 
This makes it work as expected in the minimal example now, but somehow my primary setup also started working (I had angle brackets there all along, probably did more stupid mistakes....) so I cannot reproduce the issue at all.

I initially also came here because the `<C-Enter>` binding did not work. Apparently this is a problematic combination if running (neo)vim in a terminal as it depends on the terminal emulator and how it handles it. [source](https://stackoverflow.com/questions/598113/can-terminals-detect-shift-enter-or-control-enter)

**Comment by jackMort** [comment]
Thanks, any suggestion what keys to use as default mapping for submit?

**Comment by RazaGR** [comment]
This is what I would use `  submit = "<C-a>",` 

also other which mostly map with my vim keys which I use on daily basis

```
  keymaps = {
    close = { "<C-q>" },
    submit = "<C-a>",
    yank_last = "<C-y>",
    scroll_up = "<C-k>",
    scroll_down = "<C-j>",
    toggle_settings = "<C-t>",
    new_session = "<C-n>",
    cycle_windows = "<C-c>",
    -- in the Sessions pane
    select_session = "<S-s>",
    rename_session = "<S-r>",
    delete_session = "<S-d>",
  },
```

**Comment by BradLewis** [comment]
For what it's worth, I was able to resolve this issue by altering the config for my terminal emulator (in my case Alacritty) as described in this StackOverflow [thread](https://stackoverflow.com/a/42461580/10325770).
